language: node_js
node_js:
  - node

sudo: false

cache:
  directories:
    - node_modules

before_script:
- npm install -g grunt-cli
- npm install -g codeclimate-test-reporter
- npm install

script:
- grunt build:jst
- npm test --coverage
- codeclimate-test-reporter < coverage/lcov.info
- grunt check
