<?php
// phpcs:disable Yoast.NamingConventions.NamespaceName.TooLong -- Needed in the folder structure.
// phpcs:disable Yoast.NamingConventions.NamespaceName.MaxExceeded
namespace Yoast\WP\SEO\Tests\Unit\Llms_Txt\Application\Markdown_Builders\Intro_Builder;

use Yoast\WP\SEO\Llms_Txt\Domain\Markdown\Sections\Intro;

/**
 * Tests build_intro.
 *
 * @group llms.txt
 *
 * @covers Yoast\WP\SEO\Llms_Txt\Application\Markdown_Builders\Intro_Builder::build_intro
 * @covers Yoast\WP\SEO\Llms_Txt\Application\Markdown_Builders\Intro_Builder::get_generator_version
 */
final class Build_Intro_Test extends Abstract_Intro_Builder_Test {

	/**
	 * Tests the build_description method when a Yoast sitemap exists.
	 *
	 * @return void
	 */
	public function test_build_intro() {
		$built_intro = new Intro(
			'Generated by Yoast SEO v1.0, this is an llms.txt file, meant for consumption by LLMs.',
			[]
		);
		$this->assertEquals( $built_intro, $this->instance->build_intro() );
	}
}
