export { default as edit } from "./edit.svg";
export { default as search } from "./search.svg";
export { default as angleLeft } from "./angle-left.svg";
export { default as angleRight } from "./angle-right.svg";
export { default as angleUp } from "./angle-up.svg";
export { default as angleDown } from "./angle-down.svg";
export { default as questionCircle } from "./question-circle.svg";
export { default as eye } from "./eye.svg";
export { default as circle } from "./circle.svg";
