// Action types
export const SET_ALL_DATA = "SET_ALL_DATA";
export const SET_ALL_OPTIONS = "SET_ALL_OPTIONS";

export const SET_DATA = "SET_DATA";
export const REPLACE_ARRAY_DATA = "REPLACE_ARRAY_DATA";
export const TOGGLE_DATA = "TOGGLE_DATA";

export const SET_OPTION = "SET_OPTION";

export const HANDLE_SAVE = "HANDLE_SAVE";
export const HANDLE_SAVE_REQUEST = "HANDLE_SAVE_REQUEST";
export const HANDLE_SAVE_SUCCESS = "HANDLE_SAVE_SUCCESS";
export const HANDLE_SAVE_ERROR = "HANDLE_SAVE_ERROR";

export const HANDLE_ROUTE_CHANGED = "HANDLE_ROUTE_CHANGED";
export const HANDLE_ROUTE_CHANGED_REQUEST = "HANDLE_ROUTE_CHANGED_REQUEST";
export const HANDLE_ROUTE_CHANGED_SUCCESS = "HANDLE_ROUTE_CHANGED_SUCCESS";
export const HANDLE_ROUTE_CHANGED_ERROR = "HANDLE_ROUTE_CHANGED_ERROR";

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";

export const APPLY_THEME_MODIFICATIONS = "APPLY_THEME_MODIFICATIONS";
export const APPLY_THEME_MODIFICATIONS_REQUEST = "APPLY_THEME_MODIFICATIONS_REQUEST";
export const APPLY_THEME_MODIFICATIONS_SUCCESS = "APPLY_THEME_MODIFICATIONS_SUCCESS";
export const APPLY_THEME_MODIFICATIONS_ERROR = "APPLY_THEME_MODIFICATIONS_ERROR";

export const REMOVE_THEME_MODIFICATIONS = "REMOVE_THEME_MODIFICATIONS";
export const REMOVE_THEME_MODIFICATIONS_REQUEST = "REMOVE_THEME_MODIFICATIONS_REQUEST";
export const REMOVE_THEME_MODIFICATIONS_SUCCESS = "REMOVE_THEME_MODIFICATIONS_SUCCESS";
export const REMOVE_THEME_MODIFICATIONS_ERROR = "REMOVE_THEME_MODIFICATIONS_ERROR";
