module.exports = [
	[ "accurse", "accurses", "accursing", "accursed", "accurst" ],
	[ "ache", "aches", "aching", "ached", "aken" ],
	[ "acknow", "acknows", "acknowing", "acknew", "acknown" ],
	[ "attract", "attracts", "attracting", "attracted" ],
	[ "awrath", "awraths", "awrathing", "awrathed", "awrathed" ],
	[ "bandsaw", "bandsaws", "bandsawing", "bandsawed", "bandsawn" ],
	[ "bark", "barks", "barking", "barked", "bork", "bark" ],
	[ "be", "am", "is", "are", "was", "were", "been" ],
	[ "bear", "bears", "bearing", "bore", "bare", "borne" ],
	[ "beat", "beats", "beating", "beat", "beaten" ],
	[ "beget", "begot", "begot", "begotten", "begat" ],
	[ "begin", "begins", "beginning", "began", "begun" ],
	[ "bend", "bends", "bending", "bent" ],
	[ "beware" ],
	[ "bid", "bids", "bidding", "bad", "bade", "bidden", "bide", "bided", "bode", "bode", "boden" ],
	[ "bind", "binds", "binding", "bound", "bounden" ],
	[ "bite", "bites", "biting", "bit", "bitten" ],
	[ "bleed", "bleeds", "bleeding", "bled" ],
	[ "bless", "blesses", "blessing", "blessed", "blessed", "blest" ],
	[ "blike", "blikes", "bliking", "bliked", "bloke", "blicken" ],
	[ "blin", "blins", "blinning", "blinned", "blan", "blun" ],
	[ "blive", "blives", "bliving", "blove", "bliven" ],
	[ "blow", "blows", "blowing", "blew", "blown" ],
	[ "braid", "braids", "braiding", "braided" ],
	[ "break", "breaks", "breaking", "broke", "broken" ],
	[ "breed", "breeds", "breeding", "bred" ],
	[ "bring", "brings", "bringing", "brought" ],
	[ "build", "builds", "building", "built" ],
	[ "burn", "burns", "burning", "burnt", "burned" ],
	[ "burst", "bursts", "bursting", "burst", "brast", "bursten" ],
	[ "buy", "buys", "buying", "bought" ],
	[ "can", "could" ],
	[ "caretake", "caretakes", "caretaking", "caretook", "caretaken" ],
	[ "carve", "carves", "carving", "carved", "corve", "carven", "corven" ],
	[ "cast", "casts", "casting", "casted" ],
	[ "catch", "catches", "catching", "caught" ],
	[ "chide", "chides", "chiding", "chid", "chided", "chode", "chid", "chidden" ],
	[ "choose", "chooses", "choosing", "chose", "chosen" ],
	[ "clad", "clads", "cladding", "cladded", "clothe" ],
	[ "cleave", "cleaves", "cleaving", "clove", "cleaved", "cleft", "cloven" ],
	[ "cling", "clings", "clinging", "clung" ],
	[ "clop", "clops", "clopping", "clopped" ],
	[ "cludge", "cludges", "cludged", "cludging" ],
	[ "come", "comes", "coming", "came", "comen" ],
	[ "confer", "confers", "conferring", "conferred" ],
	[ "cost", "costs", "costing", "costed" ],
	[ "creep", "creeps", "creeping", "crept", "crope", "creeped", "cropen" ],
	[ "crow", "crows", "crowing", "crowed", "crew" ],
	[ "cum", "cums", "cumming", "cummed" ],
	[ "daff", "daffs", "daffing", "daffed", "daft" ],
	[ "deal", "deals", "dealing", "dealt" ],
	[ "defer", "defers", "deferring", "deferred" ],
	[ "delve", "delves", "delving", "delved", "dalf", "dolven", "dolve" ],
	[ "depaint", "depaints", "depainting", "depainted", "depainten" ],
	[ "die", "dies", "dying", "died" ],
	[ "dig", "digs", "digging", "dug" ],
	[ "dive", "dives", "diving", "dived", "dove" ],
	[ "do", "does", "doing", "did", "done" ],
	[ "drag", "drags", "dragging", "dragged", "drug" ],
	[ "draw", "draws", "drawing", "drew", "drawn" ],
	[ "dream", "dreams", "dreaming", "dreamed", "dreamt" ],
	[ "dress", "dresses", "dressing", "dressed" ],
	[ "drink", "drinks", "drinking", "drank", "drunk" ],
	[ "drite", "drites", "driting", "drote", "drit", "dritten" ],
	[ "drive", "drives", "driving", "drove", "driven" ],
	[ "dwell", "dwells", "dwelling", "dwelt", "dwelled" ],
	[ "eat", "eats", "eating", "ate", "eaten" ],
	[ "equip", "equips", "equipping", "equipped", "equipt" ],
	[ "falchion", "falchions", "falchioning", "falchioned" ],
	[ "fall", "falls", "falling", "fell", "fallen", "felled" ],
	[ "fare", "fares", "faring", "fared", "fore", "faren" ],
	[ "feed", "feeds", "feeding", "fed" ],
	[ "feel", "feels", "feeling", "felt" ],
	[ "fight", "fights", "fighting", "fought", "foughten" ],
	[ "find", "finds", "finding", "found", "found" ],
	[ "fistfight", "fistfights", "fistfighting", "fistfought", "fistfoughten" ],
	[ "flabagast", "flabagasts", "flabagasting", "flabagasted", "flabaghast" ],
	[ "flay", "flays", "flaying", "flayed", "flain" ],
	[ "flee", "flees", "fleeing", "fled" ],
	[ "fling", "flings", "flinging", "flung" ],
	[ "flite", "flites", "fliting", "flited", "flote", "flitten" ],
	[ "fly", "flies", "flying", "flew", "flown" ],
	[ "flyblow", "flyblows", "flyblowing", "flyblew", "flyblown" ],
	[ "fold", "folds", "folding", "folded", "feld", "folden" ],
	[ "freeze", "freezes", "freezing", "froze", "frozen" ],
	[ "fret", "frets", "fretting", "fretted", "frate", "fret", "freet", "fretten" ],
	[ "gainstrive", "gainstrives", "gainstriving", "gainstrived", "gainstrove", "gainstriven" ],
	[ "get", "gets", "getting", "got", "gat", "gotten" ],
	[ "gild", "gilds", "gilding", "gilded", "gilt" ],
	[ "gin", "gins", "ginning", "gan", "gun" ],
	[ "giue", "giues", "giuing", "gaue", "giuen" ],
	[ "give", "gives", "giving", "gave", "given" ],
	[ "glide", "glides", "gliding", "glided", "glode", "glid" ],
	[ "gnaw", "gnaws", "gnawing", "gnawed", "gnawn" ],
	[ "gnide", "gnides", "gniding", "gnode", "gnidded", "gnided", "gnidden" ],
	[ "go", "goe", "goes", "going", "went", "gone" ],
	[ "grave", "graves", "graving", "graved", "grove", "graved", "graven" ],
	[ "grind", "grinds", "grinding", "ground" ],
	[ "grow", "grows", "growing", "grew", "grown", "growe", "growes", "grewe", "growne" ],
	[ "hagride", "hagrides", "hagriding", "hagrode", "hagrid", "hagridden" ],
	[ "hang", "hangs", "handing", "hung", "hanged" ],
	[ "have", "has", "having", "had" ],
	[ "hear", "hears", "hearing", "heard" ],
	[ "heave", "heaves", "heaving", "heaved", "hove", "hove", "hoven" ],
	[ "hele", "heles", "heling", "hole", "heled", "holen" ],
	[ "help", "helps", "helping", "holp", "helped", "holpen" ],
	[ "hew", "hews", "hewing", "hewed", "hewn" ],
	[ "hide", "hides", "hiding", "hid", "hidden" ],
	[ "hit", "hits", "hits", "hitting" ],
	[ "hoist", "hoists", "hoisting", "hoisted" ],
	[ "hold", "holds", "holding", "held", "holden" ],
	[ "hote", "hotes", "hoting", "hight", "hoten" ],
	[ "hould", "houlds", "houlding" ],
	[ "jailbreak", "jailbreaks", "jailbreaking", "jailbroke", "jailbroken" ],
	[ "jigsaw", "jigsaws", "jigsawing", "jigsawed", "jigsawed", "jigsawn" ],
	[ "joyride", "joyrides", "joyriding", "joyrode", "joyridden" ],
	[ "keep", "keeps", "keeping", "kept" ],
	[ "kneel", "kneels", "kneeling", "knelt", "kneeled" ],
	[ "know", "knows", "knowing", "knew", "known" ],
	[ "lade", "lades", "lading", "laded", "laden" ],
	[ "lat", "lats", "latting", "leet", "lut", "latten", "lutten" ],
	[ "lead", "leads", "leading", "led" ],
	[ "lean", "leans", "leaning", "leaned", "leant" ],
	[ "leap", "leaps", "leaping", "leaped", "lept", "leapt", "lope", "lopen" ],
	[ "learn", "learns", "learning", "learned", "learnt" ],
	[ "lemme" ],
	[ "lend", "lends", "lending", "lent" ],
	[ "lese", "leses", "lesing", "lore", "lorn" ],
	[ "let", "lets", "letting", "letten" ],
	[ "lie", "lies", "lying", "lay", "lain", "laid", "lied" ],
	[ "light", "lights", "lighting", "lit", "lighted" ],
	[ "limp", "limps", "limping", "lamp", "limped", "lump" ],
	[ "lin", "lins", "linning", "linned", "lan", "linned", "lun" ],
	[ "lose", "loses", "losing", "lost" ],
	[ "make", "makes", "making", "made" ],
	[ "may", "might" ],
	[ "mean", "means", "meaning", "meant" ],
	[ "meet", "meets", "meeting", "met" ],
	[ "melt", "melts", "melting", "melted", "molt", "molten" ],
	[ "miss", "misses", "missing", "missed" ],
	[ "mow", "mowed", "mown" ],
	[ "must" ],
	[ "need" ],
	[ "nill", "nills", "nilling", "nilled", "nould" ],
	[ "nim", "nims", "nimming", "nimmed", "nam", "numb", "nomen", "num", "nome" ],
	[ "noseride", "noserides", "noseriding", "noserode", "noseridden" ],
	[ "occur", "occurs", "occurring", "occurred" ],
	[ "ought" ],
	[ "ought", "oughts" ],
	[ "partake", "partakes", "partaking", "partook", "partaken" ],
	[ "pay", "pays", "paying", "paid", "payed" ],
	[ "piledrive", "piledrives", "piledriving", "piledrove", "piledriven" ],
	[ "plead", "pleading", "pleads", "pleaded", "pled" ],
	[ "prank", "pranks", "pranking", "pranked", "prankt" ],
	[ "pratfall", "pratfalls", "pratfalling", "pratfell", "pratfallen" ],
	[ "proove", "prooves", "prooving", "prooved", "prooven" ],
	[ "prove", "proves", "proving", "proved", "proven" ],
	[ "quethe", "quethes", "quething", "quethed", "quod", "quoth", "quethen", "queath", "queaths", "queathing", "queathed" ],
	[ "reach", "reaches", "reaching", "reached" ],
	[ "read", "reads", "reading", "read", "read" ],
	[ "refer", "refers", "referring", "referred" ],
	[ "rend", "rends", "rents", "renting", "rending", "rent" ],
	[ "revile", "reviles", "reviling", "reviled" ],
	[ "rid", "rid", "ridded", "ride", "rode", "ridden" ],
	[ "rin", "rins", "rinning", "ran", "run" ],
	[ "rine", "rines", "rining", "rined", "rone", "rinnen" ],
	[ "ring", "rings", "ringing", "rang", "rung" ],
	[ "rise", "rises", "rising", "rose", "risen" ],
	[ "rive", "rives", "riving", "rived", "rove", "rove", "riven" ],
	[ "rize", "rizes", "rizing", "roze", "rizen" ],
	[ "roadshow", "roadshows", "roadshowing", "roadshowed", "roadshown" ],
	[ "row", "rows", "rowing", "rew", "rown" ],
	[ "run", "runs", "running", "ran", "rin", "rins", "rinning" ],
	[ "sake", "sakes", "saking", "sook", "saken" ],
	[ "say", "says", "saying", "said" ],
	[ "see", "sees", "seeing", "saw", "seen", "saws", "sawing", "sawed", "sawn" ],
	[ "seek", "seeks", "seeking", "sought" ],
	[ "seethe", "seethes", "seething", "seethed", "sod", "sodden" ],
	[ "sell", "sold", "sells", "selling" ],
	[ "send", "sends", "sending", "sent" ],
	[ "set", "sets", "setting" ],
	[ "sew", "sews", "sewing", "sewed", "sewn" ],
	[ "shake", "shakes", "shaking", "shook", "shaken" ],
	[ "shall", "should" ],
	[ "shape", "shapes", "shaping", "shoop", "shaped", "shope", "shapen" ],
	[ "shave", "shaves", "shaving", "shaved", "shaven" ],
	[ "shear", "shears", "shearing", "sheared", "shore", "shorn" ],
	[ "shew", "shews", "shewing", "shewed", "shewn" ],
	[ "shine", "shines", "shining", "shone", "shined" ],
	[ "shit", "shits", "shitting", "shit", "shat", "shitted", "shit", "shitten" ],
	[ "shoe", "shoes", "shoeing", "shod", "shoed", "shodden" ],
	[ "shoot", "shoots", "shooting", "shot", "shotten" ],
	[ "show", "shows", "showing", "showed", "shown" ],
	[ "showrun", "showruns", "showrunning", "showran" ],
	[ "shred", "shreds", "shredding", "shredded", "shred" ],
	[ "shrieve", "shrieves", "shrieving", "shrieved", "shriven", "shrive", "shrives", "shriving", "shrived", "shrove", "shrived" ],
	[ "shrink", "shrinks", "shrinking", "shrank", "shrunk", "shrunken" ],
	[ "sightsee", "sightsees", "sightseeing", "sightsaw", "sightseen" ],
	[ "sing", "sings", "singing", "sang", "sung" ],
	[ "sink", "sinks", "sinking", "sank", "sunk", "sunken" ],
	[ "sit", "sits", "sitting", "sat", "seet", "sitten" ],
	[ "slay", "slays", "slaying", "slew", "slayed", "slain" ],
	[ "sleep", "sleeps", "sleeping", "slept" ],
	[ "slide", "slides", "sliding", "slid", "slidden" ],
	[ "sling", "slings", "slinging", "slung", "slong", "slongen" ],
	[ "slingshoot", "slingshoots", "slingshooting", "slingshot", "slingshotten" ],
	[ "slink", "slinks", "slinking", "slunk" ],
	[ "slip", "slips", "slipping", "slipped", "slope", "slopen" ],
	[ "slit", "slits", "slitting", "slitten", "slite", "slites", "sliting", "slote", "slited", "slited" ],
	[ "smell", "smells", "smelling", "smelled", "smelt" ],
	[ "smite", "smites", "smiting", "smote", "smitten", "smited" ],
	[ "sneak", "sneaks", "sneaking", "sneaked", "snuck" ],
	[ "sneeze", "sneezes", "sneezing", "sneezed", "snoze", "snozen" ],
	[ "snow", "snows", "snowing", "snowed", "snew", "snown" ],
	[ "solo", "soloes", "soloing", "soloed" ],
	[ "sow", "sows", "sowing", "sowed", "sown" ],
	[ "speak", "speaks", "speaking", "spoke", "spake", "spoken" ],
	[ "speed", "speeds", "speeding", "sped", "speeded" ],
	[ "speedrun", "speedruns", "speedrunning", "speedran", "speedrun" ],
	[ "spell", "spells", "spelling", "spelled", "spelt" ],
	[ "spend", "spends", "spending", "spent" ],
	[ "spill", "spills", "spilling", "spilled", "spilt" ],
	[ "spin", "spins", "spinning", "spun", "spun" ],
	[ "spit", "spits", "spitting", "spat", "spit", "spitted" ],
	[ "spoil", "spoils", "spoiling", "spoiled", "spoilt" ],
	[ "spring", "springs", "springing", "sprang", "sprung" ],
	[ "sprint", "sprints", "sprinting", "sprinted", "sprinted", "sprunt" ],
	[ "stand", "stands", "standing", "stood" ],
	[ "starve", "starves", "starving", "starved", "starf", "storven" ],
	[ "stave", "staves", "staving", "staved", "stove" ],
	[ "steal", "steals", "stealing", "stole", "stolen" ],
	[ "step", "steps", "stepping", "stepped", "stope", "stept", "stope", "stopen" ],
	[ "stick", "sticks", "sticking", "stuck" ],
	[ "sting", "stings", "stinging", "stung", "stang" ],
	[ "stink", "stinks", "stinking", "stank", "stunk" ],
	[ "straw", "straws", "strawing", "strawed", "strawn" ],
	[ "strew", "strews", "strewing", "strewed", "strewn", "strewed" ],
	[ "stride", "strides", "striding", "strode", "stridden", "strid" ],
	[ "strike", "strikes", "striking", "struck", "struck", "stricken" ],
	[ "strikethrough", "strikethroughs", "strikingthrough", "struckthrough", "strickenthrough" ],
	[ "string", "strings", "stringing", "strung" ],
	[ "strive", "strives", "striving", "strove", "strived", "striven" ],
	[ "strow", "strows", "strowing", "strowed", "strown" ],
	[ "superlie", "superlies", "superlying", "superlay", "superlain" ],
	[ "surbeat", "surbeats", "surbeating", "surbeated", "surbeaten" ],
	[ "swear", "swears", "swearing", "swore", "sworn" ],
	[ "sweep", "sweeps", "sweeping", "swept" ],
	[ "swell", "swells", "swelling", "swelled", "swollen" ],
	[ "swike", "swikes", "swiking", "swoke", "swicken" ],
	[ "swim", "swims", "swimming", "swam", "swum" ],
	[ "swing", "swings", "swinging", "swang", "swung", "swung", "swungen" ],
	[ "swink", "swinks", "swinking", "swank", "swonk", "swinkt", "swunk", "swinked", "swunken", "swonken" ],
	[ "take", "takes", "taking", "took", "taken" ],
	[ "talebear", "talebears", "talebearing", "talebore", "taleborne" ],
	[ "tattoo", "tattooes", "tattooing", "tattooed", "tattoed" ],
	[ "teach", "teaches", "teaching", "taught" ],
	[ "tear", "tears", "tearing", "tore", "torn" ],
	[ "tee", "tees", "teeing", "teed", "tow", "town" ],
	[ "tell", "told", "told" ],
	[ "thanksgive", "thanksgives", "thanksgiving", "thanksgave", "thanksgiven" ],
	[ "tharf", "tharfs", "thurving", "tharving", "thurft", "tharved" ],
	[ "think", "thinks", "thinking", "thought" ],
	[ "thread", "threads", "threading", "threaded,", "thrid", "thridden" ],
	[ "thring", "thrings", "thringing", "thrang", "thrung" ],
	[ "thrive", "thrives", "thriving", "throve", "thrived", "thriven" ],
	[ "throw", "throws", "throwing", "threw", "thrown" ],
	[ "thrust", "thrusts", "thrusting", "thrusted" ],
	[ "thunderstrike", "thunderstrikes", "thunderstriking", "thunderstruck", "thunderstricken" ],
	[ "tie", "ties", "tying", "tied" ],
	[ "tread", "treads", "treading", "trod", "trods", "trodding", "trodden" ],
	[ "tweet", "tweets", "tweeting", "tweeted", "twote", "tweeted", "twoten" ],
	[ "vie", "vies", "vying", "vied" ],
	[ "wake", "wakes", "waking", "woke", "waked", "woken", "waken", "wakens", "wakening" ],
	[ "wax", "waxes", "waxing", "waxed", "waxen" ],
	[ "wayfare", "wayfares", "wayfaring", "wayfore", "wayfared", "wayfaren" ],
	[ "wear", "wears", "wearing", "weared", "wore", "weared", "worn" ],
	[ "weave", "weaves", "weaving", "wove", "weaved", "woven" ],
	[ "weep", "weeps", "weeping", "wept" ],
	[ "will", "wills", "willing", "willed", "would" ],
	[ "win", "wins", "winning", "won" ],
	[ "wind", "winds", "winding", "wound", "winded" ],
	[ "wiredraw", "wiredraws", "wiredrawing", "wiredrew", "wiredrawn" ],
	[ "wis", "wiss", "wist", "wissed" ],
	[ "worth", "worths", "worthing", "worth", "worthed", "worthen" ],
	[ "wreak", "wreaks", "wreaking", "wreaked", "wroke", "wroken", "wrought" ],
	[ "wring", "wrings", "wringing", "wrang", "wrung", "wringed" ],
	[ "write", "writes", "writing", "wrote", "written", "writ" ],
	[ "writhe", "writhes", "writhing", "writhed", "wrothe", "writhen" ],
	[ "yelp", "yelps", "yelping", "yelped", "yolp", "yolpen" ],
	[ "yield", "yields", "yielding", "yielded", "yold", "yolden" ],
	[ "yive", "yives", "yiving", "yave", "yiven" ],
];
