module.exports = [
	// Latin: um - a, on - a
	[ "addendum", "addenda" ],
	[ "curriculum", "curricula" ],
	[ "criterion", "criteria" ],
	[ "memorandum", "memoranda" ],
	[ "ovum", "ova" ],
	[ "phenomenon", "phenomena" ],
	[ "referendum", "referenda" ],

	// Latin: a - ae
	[ "abscissa", "abscissae", "abscissæ", "abscissas" ],
	[ "agenda", "agendae", "agendæ", "agendas" ],
	[ "agora", "agorae", "agoræ" ],
	[ "ala", "alae", "alæ" ],
	[ "alga", "algae" ],
	[ "alga", "algae", "algæ" ],
	[ "alumna", "alumnae", "alumnæ" ],
	[ "amenorrhoea", "amenorrhoeae", "amenorrhoeæ", "amenorrhoeas" ],
	[ "amnesia", "amnesiae", "amnesiæ", "amnesias" ],
	[ "amoeba", "amoebae", "amoebæ", "amoebas" ],
	[ "amphora", "amphorae", "amphoræ" ],
	[ "anaethesia", "anaesthesiae", "anæsthesia", "anæsthesiæ", "anaesthesias" ],
	[ "antenna", "antennae", "antennæ", "antennas" ],
	[ "aqua", "aquae", "aquæ" ],
	[ "area", "areae", "areæ", "areas" ],
	[ "areola", "areolae", "areolæ", "areolas" ],
	[ "aula", "aulae", "aulæ", "aulas" ],
	[ "aura", "aurae", "auræ", "auras" ],
	[ "capsula", "capsulae", "capsulæ", "capsulas" ],
	[ "catapulta", "catapultae", "catapultæ", "catapultas" ],
	[ "cathedra", "cathedrae", "cathedræ", "cathedras" ],
	[ "corona", "coronae", "coronæ", "coronas" ],
	[ "diarrhoea", "diarrhoeae", "diarrhœa", "diarrhœæ", "diarrhoeas" ],
	[ "encyclopaedia", "encyclopaediae", "encyclopædia", "encyclopædiæ", "encyclopedias" ],
	[ "fabella", "fabellae", "fabellæ" ],
	[ "fibula", "fibulae", "fibulæ" ],
	[ "fistula", "fistulae", "fistulæ" ],
	[ "formula", "formulae", "formulæ", "formulas" ],
	[ "fossa", "fossae", "fossæ" ],
	[ "foveola", "foveolae", "foveolæ" ],
	[ "furcula", "furculae", "furculæ" ],
	[ "galea", "galeae", "galeæ" ],
	[ "gingiva", "gingivae", "gingivæ" ],
	[ "gonorrhoea", "gonorrhoeae", "gonorrhœa", "gonorrhœæ", "gonorrhoeas" ],
	[ "hernia", "herniae", "herniæ", "hernias" ],
	[ "hetaera", "hetaerae", "hetæra", "hetæræ", "hetaeras" ],
	[ "hora", "horae", "horæ" ],
	[ "hyaena", "hyaenae", "hyæna", "hyænæ", "hyaenas" ],
	[ "hydromedusa", "hydromedusae", "hydromedusæ" ],
	[ "hyena", "hyenae", "hyenæ", "hyenas" ],
	[ "hyperbola", "hyperbolae", "hyperbolæ", "hyperbolas" ],
	[ "idea", "ideae", "ideæ", "ideas" ],
	[ "larva", "larvae", "larvæ" ],
	[ "longa", "longae", "longæ" ],
	[ "macula", "maculae", "maculæ" ],
	[ "maxilla", "maxillae", "maxillæ" ],
	[ "maxima", "maximae", "maximæ" ],
	[ "media", "mediae", "mediæ" ],
	[ "medulla", "medullae", "medullæ" ],
	[ "medusa", "medusae", "medusæ" ],
	[ "mensa", "mensae", "mensæ" ],
	[ "metra", "metrae", "metræ" ],
	[ "microfauna", "microfaunae", "microfaunæ" ],
	[ "microflora", "microflorae", "microfloræ" ],
	[ "mina", "minae", "minæ" ],
	[ "minutia", "minutiae", "minutiæ" ],
	[ "molecula", "moleculae", "moleculæ", "moleculas" ],
	[ "monomania", "monomaniae", "monomaniæ" ],
	[ "mora", "morae", "moræ" ],
	[ "natura", "naturae", "naturæ" ],
	[ "nebula", "nebulae", "nebulæ" ],
	[ "onomatopoeia", "onomatopoeiae", "onomatopoeiæ" ],
	[ "oötheca", "oöthecae", "oöthecæ" ],
	[ "palaestra", "palaestrae", "palaestræ" ],
	[ "panacea", "panaceae", "panaceæ", "panaceas" ],
	[ "papilla", "papillae", "papillæ" ],
	[ "papilloma", "papillomae", "papillomæ", "papillomas" ],
	[ "parabola", "parabolae", "parabolæ", "parabolas" ],
	[ "paraphilia", "paraphiliae", "paraphiliæ", "paraphilias" ],
	[ "persona", "personae", "personæ", "personas" ],
	[ "pharmacopoeia", "pharmacopoeiae", "pharmacopœia", "pharmacopœiæ" ],
	[ "pinna", "pinnae", "pinnæ" ],
	[ "planta", "plantae", "plantæ" ],
	[ "pleura", "pleurae", "pleuræ" ],
	[ "pupa", "pupae", "pupæ" ],
	[ "retina", "retinae", "retinæ", "retinas" ],
	[ "saliva", "salivae", "salivæ", "salivas" ],
	[ "scapula", "scapulae", "scapulæ" ],
	[ "scrofula", "scrofulae", "scrofulæ" ],
	[ "sequela", "sequelae", "sequelæ" ],
	[ "spatula", "spatulae", "spatulæ", "spatulas" ],
	[ "spermatheca", "spermathecae", "spermathecæ" ],
	[ "squama", "squamae", "squamæ" ],
	[ "stipula", "stipulae", "stipulæ" ],
	[ "stria", "striae", "striæ" ],
	[ "subpoena", "subpoenae", "subpœna", "subpœnæ", "subpoenas" ],
	[ "summa", "summae", "summæ", "summas" ],
	[ "synaesthesia", "synaesthesiae", "synæsthesia", "synæsthesiæ", "synaesthesias" ],
	[ "taenia", "taeniae", "taeniæ" ],
	[ "testa", "testae", "testæ" ],
	[ "tibia", "tibiae", "tibiæ" ],
	[ "toga", "togae", "togæ" ],
	[ "trachea", "tracheae", "tracheæ", "tracheas" ],
	[ "ulna", "ulnae", "ulnæ" ],
	[ "urethra", "urethrae", "urethræ", "urethras" ],
	[ "uva", "uvae", "uvæ" ],
	[ "uvula", "uvulae", "uvulæ" ],
	[ "vagina", "vaginae", "vaginæ", "vaginas" ],
	[ "vertebra", "vertebrae", "vertebræ", "vertebras" ],
	[ "vesica", "vesicae", "vesicæ" ],
	[ "via", "viae", "viæ" ],
	[ "vibratiuncula", "vibratiunculae", "vibratiunculæ" ],
	[ "vita", "vitae", "vitæ" ],
	[ "vulva", "vulvae", "vulvæ", "vulvas" ],
	[ "zona", "zonae", "zonæ" ],

	// Latin: sis - ses
	[ "analysis", "analyses" ],
	[ "diagnosis", "diagnoses" ],
	[ "parenthesis", "parentheses" ],
	[ "prognosis", "prognoses" ],
	[ "synopsis", "synopses" ],
	[ "thesis", "theses" ],

	// Latin: us - ora/era
	[ "corpus", "corpora" ],
	[ "genus", "genera" ],
	[ "opus", "opera" ],

	// Latin regularized
	[ "appendix", "appendices", "appendixes" ],
	[ "cicatrix", "cicatrice", "cicatrices" ],
	[ "complex", "complexes", "complices", "complice" ],
	[ "curriculum", "curricula", "curriculums" ],
	[ "index", "indices", "indexes" ],
	[ "millennium", "millennia", "millenniums" ],
	[ "postfix", "postfices", "postfixes" ],
	[ "prefix", "prefices", "prefixes" ],
	[ "referendum", "referenda", "referendums" ],
	[ "stadium", "stadia", "stadiums" ],
	[ "suffix", "suffices", "suffixes" ],
	[ "terminus", "termini", "terminuses" ],
	[ "thesaurus", "thesauri", "thesauruses" ],

	// French
	[ "beau", "beaux" ],
	[ "chateau", "chateaux" ],
	[ "tableau", "tableaux" ],

	// Italian
	[ "libretto", "libretti" ],

	// Ch exclusions
	[ "epoch", "epochs" ],
	[ "stomach", "stomachs" ],

	// Not changing
	[ "barracks", "barracks" ],
	[ "clothes", "clothes" ],
	[ "deer", "deer" ],
	[ "series", "series" ],

	// Miscellaneous
	[ "bus", "buses" ],
	[ "child", "children" ],
	[ "circus", "circuses" ],
	[ "database", "databases" ],
	[ "echo", "echoes" ],
	[ "shoe", "shoes" ],
	[ "foot", "feet" ],
	[ "goose", "geese" ],
	[ "man", "men" ],
	[ "ox", "oxen" ],
	[ "person", "people" ],
	[ "quiz", "quizzes" ],
	[ "tooth", "teeth" ],
	[ "movie", "movies" ],
	[ "circus", "circuses" ],
	[ "status", "statuses" ],
	[ "mouse", "mice" ],
	[ "louse", "lice" ],
	[ "equinox", "equinoces" ],
];
