module.exports = [
	[ "good", "well", "better", "best" ],
	[ "red", "redder", "reddest" ],
	[ "tall", "taller", "tallest", "tally" ],
	[ "dull", "duller", "dullest", "dully" ],
	[ "bad", "badly", "worse", "worst" ],
	[ "far", "further", "father", "furthest", "farthest" ],
	[ "little", "less", "least" ],
	[ "many", "much", "more", "most" ],
	[ "bitter", "bitterer", "bitterest", "bitterly" ],
	[ "public", "publicly" ],
	[ "true", "truer", "truest", "truly" ],
	[ "fast", "faster", "fastest" ],
	[ "sole", "solely" ],
	[ "whole", "wholer", "wholest", "wholly" ],
	[ "full", "fuller", "fullest", "fully" ],
	[ "subtle", "subtler", "subtlest", "subtly" ],
	[ "gentle", "gentler", "gentlest", "gently" ],
	[ "simple", "simpler", "simplest", "simply" ],
	[ "full", "fuller", "fullest", "fully" ],
	[ "ample", "ampler", "amplest", "amply" ],
	[ "dumb", "dumber", "dumbest", "dumbly" ],
	[ "numb", "number", "numbest", "numbly" ],
	[ "political", "politically" ],
	[ "medical", "medically" ],
	[ "physical", "physically" ],
	[ "critical", "critically" ],
	[ "historical", "historically" ],
	[ "typical", "typically" ],
	[ "technical", "technically" ],
	[ "musical", "musically" ],
	[ "clinical", "clinically" ],
	[ "practical", "practically" ],
	[ "psychological", "psychologically" ],
	[ "biological", "biologically" ],
	[ "chemical", "chemically" ],
	[ "ethical", "ethically" ],
	[ "theoretical", "theoretically" ],
	[ "classical", "classically" ],
	[ "statistical", "statistically" ],
	[ "technological", "technologically" ],
	[ "mechanical", "mechanically" ],
	[ "electrical", "electrically" ],
	[ "identical", "identically" ],
	[ "ideological", "ideologically" ],
	[ "ecological", "ecologically" ],
	[ "tropical", "tropically" ],
	[ "vertical", "vertically" ],
	[ "empirical", "empirically" ],
	[ "philosophical", "philosophically" ],
	[ "theological", "theologically" ],
	[ "logical", "logically" ],
	[ "skeptical", "skeptically" ],
	[ "surgical", "surgically" ],
	[ "biblical", "biblically" ],
	[ "magical", "magically" ],
	[ "optical", "optically" ],
	[ "mathematical", "mathematically" ],
	[ "evangelical", "evangelically" ],
	[ "pharmaceutical", "pharmaceutically" ],
	[ "geographical", "geographically" ],
	[ "archaeological", "archaeologically" ],
	[ "analytical", "analytically" ],
	[ "tactical", "tactically" ],
	[ "rhetorical", "rhetorically" ],
	[ "astronomical", "astronomically" ],
	[ "cynical", "cynically" ],
	[ "theatrical", "theatrically" ],
	[ "physiological", "physiologically" ],
	[ "hypothetical", "hypothetically" ],
	[ "hierarchical", "hierarchically" ],
	[ "geological", "geologically" ],
	[ "phonological", "phonologically" ],
	[ "mystical", "mystically" ],
	[ "methodological", "methodologically" ],
	[ "numerical", "numerically" ],
	[ "hysterical", "hysterically" ],
	[ "pedagogical", "pedagogically" ],
	[ "ecumenical", "ecumenically" ],
	[ "botanical", "botanically" ],
	[ "neurological", "neurologically" ],
	[ "metaphysical", "metaphysically" ],
	[ "geopolitical", "geopolitically" ],
	[ "anthropological", "anthropologically" ],
	[ "sociological", "sociologically" ],
	[ "cervical", "cervically" ],
	[ "topical", "topically" ],
	[ "clerical", "clerically" ],
	[ "biomedical", "biomedically" ],
	[ "mythical", "mythically" ],
	[ "logistical", "logistically" ],
	[ "economical", "economically" ],
	[ "autobiographical", "autobiographically" ],
	[ "categorical", "categorically" ],
	[ "liturgical", "liturgically" ],
	[ "paradoxical", "paradoxically" ],
	[ "canonical", "canonically" ],
	[ "pathological", "pathologically" ],
	[ "metaphorical", "metaphorically" ],
	[ "epistemological", "epistemologically" ],
	[ "biographical", "biographically" ],
	[ "unethical", "unethically" ],
	[ "anatomical", "anatomically" ],
	[ "chronological", "chronologically" ],
	[ "cyclical", "cyclically" ],
	[ "lyrical", "lyrically" ],
	[ "whimsical", "whimsically" ],
	[ "ontological", "ontologically" ],
	[ "impractical", "impractically" ],
	[ "stereotypical", "stereotypically" ],
	[ "biochemical", "biochemically" ],
	[ "atypical", "atypically" ],
	[ "elliptical", "elliptically" ],
	[ "symmetrical", "symmetrically" ],
	[ "epidemiological", "epidemiologically" ],
	[ "morphological", "morphologically" ],
	[ "hypocritical", "hypocritically" ],
	[ "ecclesiastical", "ecclesiastically" ],
	[ "lexical", "lexically" ],
	[ "methodical", "methodically" ],
	[ "spherical", "spherically" ],
	[ "grammatical", "grammatically" ],
	[ "comical", "comically" ],
	[ "nautical", "nautically" ],
	[ "cylindrical", "cylindrically" ],
	[ "cosmological", "cosmologically" ],
	[ "sociopolitical", "sociopolitically" ],
	[ "satirical", "satirically" ],
	[ "allegorical", "allegorically" ],
	[ "asymmetrical", "asymmetrically" ],
	[ "mythological", "mythologically" ],
	[ "graphical", "graphically" ],
	[ "dialectical", "dialectically" ],
	[ "meteorological", "meteorologically" ],
	[ "umbilical", "umbilically" ],
	[ "neoclassical", "neoclassically" ],
	[ "fanatical", "fanatic", "fanatically" ],
	[ "encyclical", "encyclically" ],
	[ "phenomenological", "phenomenologically" ],
	[ "antithetical", "antithetically" ],
	[ "apolitical", "apolitically" ],
	[ "illogical", "illogically" ],
	[ "cortical", "cortically" ],
	[ "nonsensical", "nonsensically" ],
	[ "nonmedical", "nonmedically" ],
	[ "diabolical", "diabolically" ],
	[ "tyrannical", "tyrannically" ],
	[ "eschatological", "eschatologically" ],
	[ "conical", "conically" ],
	[ "alphabetical", "alphabetically" ],
	[ "genealogical", "genealogically" ],
	[ "fantastical", "fantastic", "fantastically" ],
	[ "prototypical", "prototypically" ],
	[ "heretical", "heretically" ],
	[ "subtropical", "subtropically" ],
	[ "acoustical", "acoustic", "acoustically" ],
	[ "pharmacological", "pharmacologically" ],
	[ "geophysical", "geophysically" ],
	[ "archeological", "archeologically" ],
	[ "polemical", "polemically" ],
	[ "radiological", "radiologically" ],
	[ "uncritical", "uncritically" ],
	[ "petrochemical", "petrochemically" ],
	[ "zoological", "zoologically" ],
	[ "topographical", "topographically" ],
	[ "quizzical", "quizzically" ],
	[ "astrophysical", "astrophysically" ],
	[ "juridical", "juridically" ],
	[ "analogical", "analogically" ],
	[ "biomechanical", "biomechanically" ],
	[ "geometrical", "geometrically" ],
	[ "hermeneutical", "hermeneutically" ],
	[ "aeronautical", "aeronautically" ],
	[ "hydrological", "hydrologically" ],
	[ "inimical", "inimically" ],
	[ "neuropsychological", "neuropsychologically" ],
	[ "puritanical", "puritanically" ],
	[ "rabbinical", "rabbinically" ],
	[ "egotistical", "egotistically" ],
	[ "microbiological", "microbiologically" ],
	[ "biophysical", "biophysically" ],
	[ "dialogical", "dialogically" ],
	[ "pontifical", "pontifically" ],
	[ "teleological", "teleologically" ],
	[ "christological", "christologically" ],
	[ "socio-political", "socio-politically" ],
	[ "alchemical", "alchemically" ],
	[ "narratological", "narratologically" ],
	[ "metrical", "metrically" ],
	[ "self-critical", "self-critically" ],
	[ "farcical", "farcically" ],
	[ "ahistorical", "ahistorically" ],
	[ "nonpolitical", "nonpolitically" ],
	[ "histological", "histologically" ],
	[ "electrochemical", "electrochemically" ],
	[ "dynamical", "dynamically" ],
	[ "exegetical", "exegetically" ],
	[ "topological", "topologically" ],
	[ "astrological", "astrologically" ],
	[ "gynecological", "gynecologically" ],
	[ "etymological", "etymologically" ],
	[ "toxicological", "toxicologically" ],
	[ "immunohistochemical", "immunohistochemically" ],
	[ "immunological", "immunologically" ],
	[ "non-political", "non-politically" ],
	[ "ecclesiological", "ecclesiologically" ],
	[ "lackadaisical", "lackadaisically" ],
	[ "preclinical", "preclinically" ],
	[ "electromechanical", "electromechanically" ],
	[ "typographical", "typographically" ],
	[ "nonclinical", "nonclinically" ],
	[ "typological", "typologically" ],
	[ "monarchical", "monarchically" ],
	[ "gerontological", "gerontologically" ],
	[ "subclinical", "subclinically" ],
	[ "non-medical", "non-medically" ],
	[ "apical", "apically" ],
	[ "indexical", "indexically" ],
	[ "helical", "helically" ],
	[ "metallurgical", "metallurgically" ],
	[ "etiological", "etiologically" ],
	[ "serological", "serologically" ],
	[ "paleontological", "paleontologically" ],
	[ "biogeochemical", "biogeochemically" ],
	[ "neurochemical", "neurochemically" ],
	[ "nonmusical", "nonmusically" ],
	[ "oratorical", "oratorically" ],
	[ "psychoanalytical", "psychoanalytically" ],
	[ "historiographical", "historiographically" ],
	[ "parenthetical", "parenthetically" ],
	[ "neotropical", "neotropically" ],
	[ "psychophysical", "psychophysically" ],
	[ "nonsurgical", "nonsurgically" ],
	[ "nontechnical", "nontechnically" ],
	[ "neurobiological", "neurobiologically" ],
	[ "ethnological", "ethnologically" ],
	[ "philological", "philologically" ],
	[ "bioethical", "bioethically" ],
	[ "photochemical", "photochemically" ],
	[ "catechetical", "catechetically" ],
	[ "neo-classical", "neo-classically" ],
	[ "non-clinical", "non-clinically" ],
	[ "rhythmical", "rhythmically" ],
	[ "climatological", "climatologically" ],
	[ "postsurgical", "postsurgically" ],
	[ "obstetrical", "obstetrically" ],
	[ "syntactical", "syntactically" ],
	[ "sceptical", "sceptically" ],
	[ "bibliographical", "bibliographically" ],
	[ "nonbiological", "nonbiologically" ],
	[ "pneumatological", "pneumatologically" ],
	[ "ornithological", "ornithologically" ],
	[ "soteriological", "soteriologically" ],
	[ "commonsensical", "commonsensically" ],
	[ "bacteriological", "bacteriologically" ],
	[ "terminological", "terminologically" ],
	[ "nonphysical", "nonphysically" ],
	[ "archetypical", "archetypically" ],
	[ "chimerical", "chimerically" ],
	[ "ethnohistorical", "ethnohistorically" ],
	[ "social-ecological", "social-ecologically" ],
	[ "histopathological", "histopathologically" ],
	[ "electrophysiological", "electrophysiologically" ],
	[ "scatological", "scatologically" ],
	[ "sociohistorical", "sociohistorically" ],
	[ "non-ideological", "non-ideologically" ],
	[ "arithmetical", "arithmetically" ],
	[ "ascetical", "ascetically" ],
	[ "historical-critical", "historical-critically" ],
	[ "geo-political", "geo-politically" ],
	[ "ecophysiological", "ecophysiologically" ],
	[ "noncritical", "noncritically" ],
	[ "urological", "urologically" ],
	[ "geochemical", "geochemically" ],
	[ "social-psychological", "social-psychologically" ],
	[ "tautological", "tautologically" ],
	[ "calendrical", "calendrically" ],
	[ "anticlerical", "anticlerically" ],
	[ "non-physical", "non-physically" ],
	[ "hemispherical", "hemispherically" ],
	[ "non-technical", "non-technically" ],
	[ "transhistorical", "transhistorically" ],
	[ "neurosurgical", "neurosurgically" ],
	[ "biogeographical", "biogeographically" ],
	[ "biotechnological", "biotechnologically" ],
	[ "neurophysiological", "neurophysiologically" ],
	[ "transtheoretical", "transtheoretically" ],
	[ "uneconomical", "uneconomically" ],
	[ "nonideological", "nonideologically" ],
	[ "mission-critical", "mission-critically" ],
	[ "dermatological", "dermatologically" ],
	[ "extramusical", "extramusically" ],
	[ "ungrammatical", "ungrammatically" ],
	[ "social-political", "social-politically" ],
	[ "nutraceutical", "nutraceutically" ],
	[ "psychopathological", "psychopathologically" ],
	[ "logical-mathematical", "logical-mathematically" ],
	[ "criminological", "criminologically" ],
	[ "nonhierarchical", "nonhierarchically" ],
	[ "socio-historical", "socio-historically" ],
	[ "tropological", "tropologically" ],
	[ "piratical", "piratically" ],
	[ "phytochemical", "phytochemically" ],
	[ "psychophysiological", "psychophysiologically" ],
	[ "semi-autobiographical", "semi-autobiographically" ],
	[ "museological", "museologically" ],
	[ "hematological", "hematologically" ],
	[ "haematological", "haematologically" ],
	[ "ical", "ically" ],
	[ "subcortical", "subcortically" ],
	[ "supercritical", "supercritically" ],
	[ "world-historical", "world-historically" ],
	[ "quantum-mechanical", "quantum-mechanically" ],
	[ "ototopical", "ototopically" ],
	[ "microsurgical", "microsurgically" ],
	[ "nonchemical", "nonchemically" ],
	[ "non-typical", "non-typically" ],
	[ "mineralogical", "mineralogically" ],
	[ "entomological", "entomologically" ],
	[ "parasitical", "parasitically" ],
	[ "anti-clerical", "anti-clerically" ],
	[ "countercyclical", "countercyclically" ],
	[ "near-vertical", "near-vertically" ],
	[ "semitropical", "semitropically" ],
	[ "viatical", "viatically" ],
	[ "biopolitical", "biopolitically" ],
	[ "biopharmaceutical", "biopharmaceutically" ],
	[ "pathophysiological", "pathophysiologically" ],
	[ "cubical", "cubically" ],
	[ "ethnobotanical", "ethnobotanically" ],
	[ "gastronomical", "gastronomically" ],
	[ "hagiographical", "hagiographically" ],
	[ "microelectromechanical", "microelectromechanically" ],
	[ "semiclassical", "semiclassically" ],
	[ "semiautobiographical", "semiautobiographically" ],
	[ "nontypical", "nontypically" ],
	[ "near-identical", "near-identically" ],
	[ "ethnographical", "ethnographically" ],
	[ "socioecological", "socioecologically" ],
	[ "post-surgical", "post-surgically" ],
	[ "phenological", "phenologically" ],
	[ "sociobiological", "sociobiologically" ],
	[ "all-optical", "all-optically" ],
	[ "astronautical", "astronautically" ],
	[ "deontological", "deontologically" ],
	[ "hypercritical", "hypercritically" ],
	[ "iconographical", "iconographically" ],
	[ "vocational-technical", "vocational-technically" ],
	[ "non-surgical", "non-surgically" ],
	[ "non-pharmacological", "non-pharmacologically" ],
	[ "non-biological", "non-biologically" ],
	[ "physicochemical", "physicochemically" ],
	[ "medical-surgical", "medical-surgically" ],
	[ "metonymical", "metonymically" ],
	[ "geotechnical", "geotechnically" ],
	[ "cultural-historical", "cultural-historically" ],
	[ "phantasmagorical", "phantasmagorically" ],
	[ "religio-political", "religio-politically" ],
	[ "pre-clinical", "pre-clinically" ],
	[ "phylogeographical", "phylogeographically" ],
	[ "non-critical", "non-critically" ],
	[ "noncanonical", "noncanonically" ],
	[ "unmusical", "unmusically" ],
	[ "clinicopathological", "clinicopathologically" ],
	[ "geomorphological", "geomorphologically" ],
	[ "musicological", "musicologically" ],
	[ "characterological", "characterologically" ],
	[ "thermomechanical", "thermomechanically" ],
	[ "seismological", "seismologically" ],
	[ "psychopharmacological", "psychopharmacologically" ],
	[ "nonclassical", "nonclassically" ],
	[ "oncological", "oncologically" ],
	[ "unhistorical", "unhistorically" ],
	[ "micromechanical", "micromechanically" ],
	[ "nanomechanical", "nanomechanically" ],
	[ "embryological", "embryologically" ],
	[ "dramaturgical", "dramaturgically" ],
	[ "social-historical", "social-historically" ],
	[ "socio-ecological", "socio-ecologically" ],
	[ "sublexical", "sublexically" ],
	[ "premedical", "premedically" ],
	[ "numerological", "numerologically" ],
	[ "sociopsychological", "sociopsychologically" ],
	[ "veridical", "veridically" ],
	[ "bioidentical", "bioidentically" ],
	[ "anarchical", "anarchically" ],
	[ "anti-political", "anti-politically" ],
	[ "military-political", "military-politically" ],
	[ "mycological", "mycologically" ],
	[ "monological", "monologically" ],
	[ "gynaecological", "gynaecologically" ],
	[ "parapsychological", "parapsychologically" ],
	[ "poutical", "poutically" ],
	[ "postbiological", "postbiologically" ],
	[ "post-metaphysical", "post-metaphysically" ],
	[ "phrenological", "phrenologically" ],
	[ "physico-chemical", "physico-chemically" ],
	[ "non-hierarchical", "non-hierarchically" ],
	[ "virological", "virologically" ],
	[ "magneto-optical", "magneto-optically" ],
	[ "agroecological", "agroecologically" ],
	[ "atheoretical", "atheoretically" ],
	[ "audiological", "audiologically" ],
	[ "axiological", "axiologically" ],
	[ "mytho-empirical", "mytho-empirically" ],
	[ "noncategorical", "noncategorically" ],
	[ "non-musical", "non-musically" ],
	[ "postclassical", "postclassically" ],
	[ "penological", "penologically" ],
	[ "osteological", "osteologically" ],
	[ "socio-psychological", "socio-psychologically" ],
	[ "semiological", "semiologically" ],
	[ "electro-optical", "electro-optically" ],
	[ "ethnopolitical", "ethnopolitically" ],
	[ "electro-chemical", "electro-chemically" ],
	[ "ecohydrological", "ecohydrologically" ],
	[ "horological", "horologically" ],
	[ "subcritical", "subcritically" ],
	[ "taxonomical", "taxonomic", "taxonomically" ],
	[ "non-classical", "non-classically" ],
	[ "nonempirical", "nonempirically" ],
	[ "pre-political", "pre-politically" ],
	[ "psycho-physical", "psycho-physically" ],
	[ "rheological", "rheologically" ],
	[ "non-empirical", "non-empirically" ],
	[ "gastroenterological", "gastroenterologically" ],
	[ "neuroanatomical", "neuroanatomically" ],
	[ "missiological", "missiologically" ],
	[ "literary-historical", "literary-historically" ],
	[ "demographical", "demographically" ],
	[ "ethnomusicological", "ethnomusicologically" ],
	[ "bioelectrical", "bioelectrically" ],
	[ "ethological", "ethologically" ],
	[ "endocrinological", "endocrinologically" ],
	[ "gemological", "gemologically" ],
	[ "extratropical", "extratropically" ],
	[ "periodical", "periodic",	"periodically" ],
	[ "pomological", "pomologically" ],
	[ "theosophical", "theosophically" ],
	[ "unbiblical", "unbiblically" ],
	[ "semi-tropical", "semi-tropically" ],
	[ "oligarchical", "oligarchically" ],
	[ "non-canonical", "non-canonically" ],
	[ "nonoptical", "nonoptically" ],
	[ "metatheatrical", "metatheatrically" ],
	[ "neocortical", "neocortically" ],
	[ "electrosurgical", "electrosurgically" ],
	[ "doxological", "doxologically" ],
	[ "bio-medical", "bio-medically" ],
	[ "andragogical", "andragogically" ],
	[ "aetiological", "aetiologically" ],
	[ "biotechnical", "biotechnically" ],
	[ "micro-political", "micro-politically" ],
	[ "intermusical", "intermusically" ],
	[ "nonhistorical", "nonhistorically" ],
	[ "phenotypical", "phenotypically" ],
	[ "photomechanical", "photomechanically" ],
	[ "early", "earlier", "earliest" ],
	[ "likely", "likelier", "likeliest" ],
	[ "daily", "dailier", "dailiest" ],
	[ "holy", "holier", "holiest" ],
	[ "friendly", "friendlier", "friendliest" ],
	[ "weekly", "weeklier", "weekliest" ],
	[ "lovely", "lovelier", "loveliest" ],
	[ "ugly", "uglier", "ugliest" ],
	[ "monthly", "monthlier", "monthliest" ],
	[ "deadly", "deadlier", "deadliest" ],
	[ "silly", "sillier", "silliest" ],
	[ "lonely", "lonelier", "loneliest" ],
	[ "costly", "costlier", "costliest" ],
	[ "lively", "livelier", "liveliest" ],
	[ "timely", "timelier", "timeliest" ],
	[ "chilly", "chillier", "chilliest" ],
	[ "curly", "curlier", "curliest" ],
	[ "nightly", "nightlier", "nightliest" ],
	[ "yearly", "yearlier", "yearliest" ],
	[ "sly", "slier", "sliest" ],
	[ "earthly", "earthlier", "earthliest" ],
	[ "worldly", "worldlier", "worldliest" ],
	[ "ghostly", "ghostlier", "ghostliest" ],
	[ "oily", "oilier", "oiliest" ],
	[ "stately", "statelier", "stateliest" ],
	[ "prickly", "pricklier", "prickliest" ],
	[ "hourly", "hourlier", "hourliest" ],
	[ "grizzly", "grizzlier", "grizzliest" ],
	[ "jolly", "jollier", "jolliest" ],
	[ "burly", "burlier", "burliest" ],
	[ "sickly", "sicklier", "sickliest" ],
	[ "bubbly", "bubblier", "bubbliest" ],
	[ "wobbly", "wobblier", "wobbliest" ],
	[ "manly", "manlier", "manliest" ],
	[ "ghastly", "ghastlier", "ghastliest" ],
	[ "steely", "steelier", "steeliest" ],
	[ "grisly", "grislier", "grisliest" ],
	[ "smelly", "smellier", "smelliest" ],
	[ "hilly", "hillier", "hilliest" ],
	[ "woolly", "woollier", "woolliest" ],
	[ "surly", "surlier", "surliest" ],
	[ "spindly", "spindlier", "spindliest" ],
	[ "homely", "homelier", "homeliest" ],
	[ "courtly", "courtlier", "courtliest" ],
	[ "priestly", "priestlier", "priestliest" ],
	[ "wily", "wilier", "wiliest" ],
	[ "pearly", "pearlier", "pearliest" ],
	[ "shapely", "shapelier", "shapeliest" ],
	[ "sparkly", "sparklier", "sparkliest" ],
	[ "deathly", "deathlier", "deathliest" ],
	[ "portly", "portlier", "portliest" ],
	[ "frilly", "frillier", "frilliest" ],
	[ "gangly", "ganglier", "gangliest" ],
	[ "crumbly", "crumblier", "crumbliest" ],
	[ "saintly", "saintlier", "saintliest" ],
	[ "scaly", "scalier", "scaliest" ],
	[ "godly", "godlier", "godliest" ],
	[ "princely", "princelier", "princeliest" ],
	[ "gravelly", "gravellier", "gravelliest" ],
	[ "scraggly", "scragglier", "scraggliest" ],
	[ "bristly", "bristlier", "bristliest" ],
	[ "girly", "girlier", "girliest" ],
	[ "comely", "comelier", "comeliest" ],
	[ "sprightly", "sprightlier", "sprightliest" ],
	[ "goodly", "goodlier", "goodliest" ],
	[ "beastly", "beastlier", "beastliest" ],
	[ "squiggly", "squigglier", "squiggliest" ],
	[ "crinkly", "crinklier", "crinkliest" ],
	[ "philly", "phillier", "philliest" ],
	[ "mealy", "mealier", "mealiest" ],
	[ "pebbly", "pebblier", "pebbliest" ],
	[ "wifely", "wifelier", "wifeliest" ],
	[ "lordly", "lordlier", "lordliest" ],
	[ "bluntly", "bluntlier", "bluntliest" ],
	[ "kingly", "kinglier", "kingliest" ],
	[ "wrinkly", "wrinklier", "wrinkliest" ],
	[ "wooly", "woolier", "wooliest" ],
	[ "drizzly", "drizzlier", "drizzliest" ],
	[ "stubbly", "stubblier", "stubbliest" ],
	[ "seely", "seelier", "seeliest" ],
	[ "pimply", "pimplier", "pimpliest" ],
	[ "wiggly", "wigglier", "wiggliest" ],
	[ "twinkly", "twinklier", "twinkliest" ],
	[ "knightly", "knightlier", "knightliest" ],
	[ "straggly", "stragglier", "straggliest" ],
	[ "giggly", "gigglier", "giggliest" ],
	[ "dangly", "danglier", "dangliest" ],
	[ "swirly", "swirlier", "swirliest" ],
	[ "jiggly", "jigglier", "jiggliest" ],
	[ "treacly", "treaclier", "treacliest" ],
	[ "dilly", "dillier", "dilliest" ],
	[ "snuggly", "snugglier", "snuggliest" ],
	[ "fiddly", "fiddlier", "fiddliest" ],
	[ "rattly", "rattlier", "rattliest" ],
];
