module.exports = [
	[ "abear", "abears", "abearing", "abore", "aborn", "aborne" ],
	[ "abide", "abides", "abiding", "abode", "abided", "abidden" ],
	[ "abite", "abites", "abiting", "abit", "abitten" ],
	[ "accurse", "accurses", "accursing", "accursed", "accurst" ],
	[ "ache", "aches", "aching", "ached", "aken" ],
	[ "acknow", "acknows", "acknowing", "acknew", "acknown" ],
	[ "adraw", "adraws", "adrawing", "adrew", "adrawn" ],
	[ "afare", "afares", "afaring", "afared", "afore", "afaren" ],
	[ "aftersee", "aftersees", "afterseeing", "aftersaw", "afterseen" ],
	[ "aknow", "aknows", "aknowing", "aknew", "aknown" ],
	[ "arise", "arises", "arising", "arose", "arisen" ],
	[ "arize", "arizes", "arizing", "aroze", "arizen" ],
	[ "atgo", "atgoes", "atgoing", "atwent", "atgone" ],
	[ "atride", "atrides", "atriding", "atrode", "atridden" ],
	[ "atrin", "atrins", "atrinning", "atran", "atrun" ],
	[ "atrine", "atrines", "atrining", "atrined", "atrone", "atrinnen" ],
	[ "atsake", "atsakes", "atsaking", "atsook", "atsaken" ],
	[ "atshake", "atshakes", "atshaking", "atshook", "atshaken" ],
	[ "atsit", "atsits", "atsitting", "atsat", "atseet", "atsitten" ],
	[ "atslip", "atslips", "atslipping", "atslipped", "atslope", "atslopen" ],
	[ "autohide", "autohides", "autohiding", "autohid", "autohidden" ],
	[ "autorun", "autoruns", "autorunning", "autoran", "autorun" ],
	[ "awake", "awakes", "awaking", "awoke", "awaked", "awoken", "awaken", "awakens", "awakening", ],
	[ "awrath", "awraths", "awrathing", "awrathed", "awrathed" ],
	[ "ayield", "ayields", "ayielding", "ayielded", "ayold", "ayolden" ],
	[ "back-bite", "back-bites", "back-biting", "back-bit", "back-bitten" ],
	[ "backbite", "backbites", "backbiting", "backbit", "backbitten" ],
	[ "backshine", "backshines", "backshining", "backshone", "backshined" ],
	[ "backslide", "backslides", "backsliding", "backslid", "backslidden" ],
	[ "bandsaw", "bandsaws", "bandsawing", "bandsawed", "bandsawn" ],
	[ "beat", "beats", "beating", "beaten" ],
	[ "bebark", "bebarks", "bebarking", "bebarked", "bebork", "bebark" ],
	[ "bebless", "beblesses", "beblessing", "beblessed", "beblessed", "beblest" ],
	[ "beblow", "beblows", "beblowing", "beblew", "beblown" ],
	[ "bebreak", "bebreaks", "bebreaking", "bebroke", "bebroken" ],
	[ "becarve", "becarves", "becarving", "becorve", "becarved", "becorven" ],
	[ "become", "becomes", "becoming", "became", "become" ],
	[ "bedaff", "bedaffs", "bedaffing", "bedaffed", "bedaft" ],
	[ "bedelve", "bedelves", "bedelving", "bedelved", "bedolve", "bedolven" ],
	[ "bedo", "bedoes", "bedoing", "bedid", "bedone" ],
	[ "bedraw", "bedraws", "bedrawing", "bedrew", "bedrawn" ],
	[ "bedrink", "bedrinks", "bedrinking", "bedrank", "bedrunk" ],
	[ "bedrite", "bedrites", "bedriting", "bedrote", "bedrit", "bedritten" ],
	[ "bedrive", "bedrives", "bedriving", "bedrove", "bedriven" ],
	[ "befall", "befalls", "befalling", "befell", "befallen" ],
	[ "beflay", "beflays", "beflaying", "beflayed", "beflain" ],
	[ "befly", "beflies", "beflying", "beflew", "beflown" ],
	[ "befold", "befolds", "befolding", "befolded", "befeld", "befolden" ],
	[ "beget", "begets", "begetting", "begot", "begat", "begotten" ],
	[ "begin", "begins", "beginning", "began", "begun" ],
	[ "begive", "begives", "begiving", "begave", "begiven" ],
	[ "bego", "begoes", "begoing", "bewent", "begone" ],
	[ "behelp", "behelps", "behelping", "behelped" ],
	[ "behew", "behews", "behewing", "behewed", "behewn" ],
	[ "behold", "beholds", "beholding", "beheld", "beholden" ],
	[ "beknow", "beknows", "beknowing", "beknew", "beknown" ],
	[ "belawgive", "belawgives", "belawgiving", "belawgave", "belawgiven" ],
	[ "belimp", "belimps", "belimping", "belamp", "belimped", "belump" ],
	[ "belive", "belives", "beliving", "belove", "beliven" ],
	[ "bename", "benames", "benaming", "benamed", "benempt" ],
	[ "benim", "benims", "benimming", "benam", "benimmed", "benomen", "benome" ],
	[ "bequeath", "bequeaths", "bequeathing", "bequeathed", "bequoth", "bequethen" ],
	[ "beride", "berides", "beriding", "berode", "beridden" ],
	[ "besee", "besees", "beseeing", "besaw", "beseen" ],
	[ "beseech", "beseechs", "beseeching", "beseeched", "besought" ],
	[ "beshake", "beshakes", "beshaking", "beshook", "beshaken" ],
	[ "beshear", "beshears", "beshearing", "beshore", "besheared", "beshorn" ],
	[ "beshite", "beshites", "beshiting", "beshit", "beshote", "beshat", "beshitten" ],
	[ "besing", "besings", "besinging", "besang", "besung" ],
	[ "besit", "besits", "besitting", "besat", "besat", "besitten" ],
	[ "bespeak", "bespeaks", "bespeaking", "bespoke", "bespake", "bespoken" ],
	[ "bespit", "bespits", "bespitting", "bespat", "bespit", "bespitted" ],
	[ "besteal", "besteals", "bestealing", "bestole", "bestolen" ],
	[ "bestep", "besteps", "bestepping", "bestepped", "bestope", "bestept", "bestope", "bestopen" ],
	[ "bestrew", "bestrews", "bestrewing", "bestrewed", "bestrewn" ],
	[ "bestride", "bestrides", "bestriding", "bestrode", "bestridden", "bestrid" ],
	[ "beswike", "beswikes", "beswiking", "beswoke", "beswicken" ],
	[ "beswink", "beswinks", "beswinking", "beswank", "beswunk", "beswunken" ],
	[ "betake", "betakes", "betaking", "betook", "betaken" ],
	[ "betee", "betees", "beteeing", "beteed", "betow", "betown" ],
	[ "bethrow", "bethrows", "bethrowing", "bethrew", "bethrown" ],
	[ "betread", "betreads", "betreading", "betrod", "betrodden" ],
	[ "bewrite", "bewrites", "bewriting", "bewrote", "bewritten" ],
	[ "beyelp", "beyelps", "beyelping", "beyelped", "beyolp", "beyolpen" ],
	[ "bide", "bides", "biding", "bode", "bided", "bidden", "bede", "bedes", "beding", "bade", "boden" ],
	[ "bind", "binds", "binding", "bound", "bounden" ],
	[ "bite", "bites", "biting", "bit", "bitten" ],
	[ "blike", "blikes", "bliking", "bliked", "bloke", "blicken" ],
	[ "blin", "blins", "blinning", "blinned", "blan", "blun" ],
	[ "blive", "blives", "bliving", "blove", "bliven" ],
	[ "blow", "blows", "blowing", "blew", "blown" ],
	[ "braid", "braids", "braiding", "braided" ],
	[ "break", "breaks", "breaking", "broke", "broken" ],
	[ "break-up", "break-ups", "breaking-up", "broke-up", "broken-up" ],
	[ "brow-beat", "brow-beats", "brow-beating", "brow-beaten" ],
	[ "browbeat", "browbeats", "browbeating", "browbeat", "browbeaten" ],
	[ "burst", "bursts", "bursting", "brast", "bursten" ],
	[ "buy", "buys", "buying", "bought" ],
	[ "caretake", "caretakes", "caretaking", "caretook", "caretaken" ],
	[ "carve", "carves", "carving", "carved", "corve", "carven", "corven" ],
	[ "chide", "chides", "chiding", "chid,", "chided,", "chode", "chid", "chidden" ],
	[ "choose", "chooses", "choosing", "chose", "chosen" ],
	[ "clepe", "clepes", "cleping", "cleped,", "clepen", "clept" ],
	[ "clop", "clops", "clopping", "clopped" ],
	[ "cludge", "cludges", "cludged", "cludging" ],
	[ "co-write", "co-writes", "co-writing", "co-wrote", "co-written" ],
	[ "come", "comes", "coming", "came", "comen" ],
	[ "copywrite", "copywrites", "copywriting", "copywrote", "copywritten" ],
	[ "counterattract", "counterattracts", "counterattracting", "counterattracted" ],
	[ "counterdraw", "counterdraws", "counterdrawing", "counterdrew", "counterdraw" ],
	[ "countersing", "countersings", "countersinging", "countersang", "countersung" ],
	[ "countersink", "countersinks", "countersinking", "countersank", "countersunk" ],
	[ "cowrite", "cowrites", "cowriting", "cowrote", "cowritten" ],
	[ "creep", "creeps", "creeping", "crept", "crope", "creeped", "cropen" ],
	[ "crossbite", "crossbites", "crossbiting", "crossbit", "crossbitten" ],
	[ "crow", "crows", "crowing", "crowed", "crew" ],
	[ "cum", "cums", "cumming", "cummed" ],
	[ "deep-freeze", "deep-freezes", "deep-freezing", "deep-froze", "deep-freezed", "deep-frozen" ],
	[ "delve", "delves", "delving", "delved", "dalf", "dolven" ],
	[ "depaint", "depaints", "depainting", "depainted", "depainten" ],
	[ "disbecome", "disbecomes", "disbecoming", "disbecame" ],
	[ "disprove", "disproves", "disproving", "disproved", "disproven" ],
	[ "do", "does", "doing", "did", "done" ],
	[ "downbear", "downbears", "downbearing", "downbore", "downborne" ],
	[ "downcome", "downcomes", "downcoming", "downcame" ],
	[ "downdraw", "downdraws", "downdrawing", "downdrew", "downdrawn" ],
	[ "downfall", "downfalls", "downfalling", "downfell", "downfallen" ],
	[ "downtrod", "downtrods", "downtrodding", "downtrod", "downtrodden" ],
	[ "draw", "draws", "drawing", "drew", "drawn" ],
	[ "dress", "dresses", "dressing", "dressed" ],
	[ "drink", "drinks", "drinking", "drank", "drunk" ],
	[ "drite", "drites", "driting", "drate", "dritten" ],
	[ "drive", "drives", "driving", "drove", "driven" ],
	[ "eat", "eats", "eating", "ate", "eaten" ],
	[ "enblow", "enblows", "enblowing", "enblew", "enblown" ],
	[ "enfreeze", "enfreezes", "enfreezing", "enfroze", "enfrozen" ],
	[ "entertake", "entertakes", "entertaking", "entertook", "entertaken" ],
	[ "enwrite", "enwrites", "enwriting", "enwrote", "enwritten" ],
	[ "equip", "equips", "equipping", "equipped", "equipt" ],
	[ "falchion", "falchions", "falchioning", "falchioned" ],
	[ "fall", "falls", "falling", "fell", "fallen", "felled" ],
	[ "fare", "fares", "faring", "fared", "fore", "faren" ],
	[ "farsee", "farsees", "farseeing", "farsaw", "farseen" ],
	[ "farspeak", "farspeaks", "farspeaking", "farspoke", "farspoken" ],
	[ "fight", "fights", "fighting", "fought", "fought", "foughten" ],
	[ "find", "finds", "finding", "found", "found" ],
	[ "finedraw", "finedraws", "finedrawing", "finedrew", "finedrawn" ],
	[ "fistfight", "fistfights", "fistfighting", "fistfought", "fistfoughten" ],
	[ "flabagast", "flabagasts", "flabagasting", "flabagasted", "flabaghast" ],
	[ "flite", "flites", "fliting", "flited", "flote", "flitten" ],
	[ "flyblow", "flyblows", "flyblowing", "flyblew", "flyblown" ],
	[ "forbear", "forbears", "forbearing", "forbore", "forborne" ],
	[ "forbeat", "forbeats", "forbeating", "forbeat", "forbeaten" ],
	[ "forbid", "forbids", "forbidding", "forbid", "forbad", "forbade", "forbidden" ],
	[ "forbite", "forbites", "forbiting", "forbit", "forbitten" ],
	[ "forbreak", "forbreaks", "forbreaking", "forbroke", "forbroken" ],
	[ "forburst", "forbursts", "forbursting", "forburst", "forbrast", "forbursten" ],
	[ "forcarve", "forcarves", "forcarving", "forcorve", "forcarved", "forcorven" ],
	[ "forcleave", "forcleaves", "forcleaving", "forclove", "forcloven" ],
	[ "fordo", "fordoes", "fordoing", "fordid", "fordone" ],
	[ "fordrive", "fordrives", "fordriving", "fordrove", "fordriven" ],
	[ "forebear", "forebears", "forebearing", "forebore", "foreborne" ],
	[ "forebite", "forebites", "forebiting", "forebit", "forebitten" ],
	[ "forechoose", "forechooses", "forechoosing", "forechose", "forechosen" ],
	[ "foredo", "foredoes", "foredoing", "foredid", "foredone" ],
	[ "foredraw", "foredraws", "foredrawing", "foredrew", "foredrawn" ],
	[ "forego", "foregoes", "foregoing", "forewent", "foregone" ],
	[ "forehew", "forehews", "forehewing", "forehewed", "forehewn" ],
	[ "forehold", "foreholds", "foreholding", "foreheld", "foreholden" ],
	[ "foreknow", "foreknows", "foreknowing", "foreknew", "foreknown" ],
	[ "forelie", "forelies", "forelying", "forelay", "forelain" ],
	[ "forerun", "foreruns", "forerunning", "foreran", "forerun" ],
	[ "foresee", "foresees", "foreseeing", "foresaw", "foreseen" ],
	[ "foreshape", "foreshapes", "foreshaping", "foreshaped", "foreshope", "foreshapen" ],
	[ "foreshew", "foreshews", "foreshewing", "foreshewed", "foreshewn" ],
	[ "foreshow", "foreshows", "foreshowing", "foreshowed", "foreshown" ],
	[ "forespeak", "forespeaks", "forespeaking", "forespoke", "forespoken" ],
	[ "foreswear", "foreswears", "foreswears", "foreswore", "foresworn" ],
	[ "foretake", "foretakes", "foretaking", "foretook", "foretaken" ],
	[ "forfight", "forfights", "forfighting", "forfought", "forfoughten" ],
	[ "forfret", "forfrets", "forfretting", "forfretted,", "forfreet,", "forfrate", "forfretten" ],
	[ "forget", "forgets", "forgetting", "forgot", "forgotten" ],
	[ "forgive", "forgives", "forgiving", "forgave", "forgiven" ],
	[ "forgnide", "forgnides", "forgniding", "forgnode", "forgnided", "forgnidden" ],
	[ "forgo", "forgoes", "forgoing", "forwent", "forgone" ],
	[ "forgrow", "forgrows", "forgrowing", "forgrew", "forgrown" ],
	[ "forhele", "forheles", "forheling", "forhole", "forholen" ],
	[ "forhold", "forholds", "forholding", "forheld", "forholden" ],
	[ "forlat", "forlats", "forlatting", "forleet", "forlut", "forlatten", "forlutten" ],
	[ "forlese", "forleses", "forlesing", "forlore", "forlorn" ],
	[ "forlie", "forlies", "forlying", "forlay", "forlain" ],
	[ "formelt", "formelts", "formelting", "formelted", "formolt", "formolten" ],
	[ "fornim", "fornims", "fornimming", "fornam", "fornimmed", "fornum", "fornumb" ],
	[ "forsake", "forsakes", "forsaking", "forsook", "forsaken" ],
	[ "forsee", "forsees", "forseeing", "forsaw", "forseen" ],
	[ "forshake", "forshakes", "forshaking", "forshook", "forshaken" ],
	[ "forshape", "forshapes", "forshaping", "forshoop", "forshaped", "forshope", "forshapen" ],
	[ "forshrink", "forshrinks", "forshrinking", "forshrank", "forshrunk", "forshrunken" ],
	[ "forsing", "forsings", "forsinging", "forsang", "forsung" ],
	[ "forsling", "forslings", "forslinging", "forslung", "forslong", "forslongen" ],
	[ "forsmite", "forsmites", "forsmiting", "forsmote", "forsmitten" ],
	[ "forspeak", "forspeaks", "forspeaking", "forspoke", "forspoken" ],
	[ "forsteal", "forsteals", "forstealing", "forstole", "forstolen" ],
	[ "forswear", "forswears", "forswearing", "forswore", "forsworn" ],
	[ "forswing", "forswings", "forswinging", "forswang", "forswung", "forswungen" ],
	[ "forswink", "forswinks", "forswinking", "forswank", "forswonk", "forswunken", "forswunk" ],
	[ "fortake", "fortakes", "fortaking", "fortook", "fortaken" ],
	[ "fortear", "fortears", "fortearing", "fortore", "fortorn" ],
	[ "fortee", "fortees", "forteeing", "forteed", "fortow", "fortown" ],
	[ "forthbear", "forthbears", "forthbearing", "forthbore", "forthborn" ],
	[ "forthcome", "forthcomes", "forthcoming", "forthcame" ],
	[ "forthdraw", "forthdraws", "forthdrawing", "forthdrew", "forthdrawn" ],
	[ "forthgo", "forthgoes", "forthgoing", "forthwent", "forthgone" ],
	[ "forthnim", "forthnims", "forthnimming", "forthnam", "forthnimmed", "forthnum", "forthnumb" ],
	[ "forthrow", "forthrows", "forthrowing", "forthrew", "forthrown" ],
	[ "forthshow", "forthshows", "forthshowing", "forthshowed", "forthshown" ],
	[ "forthspeak", "forthspeaks", "forthspeaking", "forthspoke", "forthspoken" ],
	[ "fortread", "fortreads", "fortreading", "fortrod", "fortrodden" ],
	[ "forwax", "forwaxes", "forwaxing", "forwaxed", "forwaxen" ],
	[ "forwear", "forwears", "forwearing", "forwore", "forworn" ],
	[ "forworth", "forworths", "forworthing", "forworthed", "forword", "forworden", "forworthen" ],
	[ "foryield", "foryields", "foryielding", "foryold", "foryielded", "foryolden", "foryielded" ],
	[ "freefall", "freefalls", "freefalling", "freefell", "freefallen" ],
	[ "freeride", "freerides", "freeriding", "freerode", "freeridden" ],
	[ "freerun", "freeruns", "freerunning", "freeran" ],
	[ "freeze", "freezes", "freezing", "froze", "frozen" ],
	[ "fret", "frets", "fretting", "fretted", "frate", "fret", "freet", "fretten" ],
	[ "frostbite", "frostbites", "frostbiting", "frostbit", "frostbitten" ],
	[ "fullcome", "fullcomes", "fullcoming", "fullcame", "fullcome" ],
	[ "fulldo", "fulldoes", "fulldoing", "fulldid", "fulldone" ],
	[ "gainstrive", "gainstrives", "gainstriving", "gainstrived", "gainstrove", "gainstriven" ],
	[ "get", "gets", "getting", "got", "gotten" ],
	[ "giue", "giues", "giuing", "gaue", "giuen" ],
	[ "give", "gives", "giving", "gave", "given" ],
	[ "glide", "glides", "gliding", "glided", "glode", "glid" ],
	[ "gnaw", "gnaws", "gnawing", "gnawed", "gnawn" ],
	[ "gnide", "gnides", "gniding", "gnode", "gnidded", "gnided", "gnidden" ],
	[ "go", "goes", "going", "went", "gone" ],
	[ "grave", "graves", "graving", "graved", "grove", "graved", "graven" ],
	[ "grow", "grows", "growing", "grew", "grown", "growe", "growes", "grewe", "growne" ],
	[ "hagride", "hagrides", "hagriding", "hagrode", "hagrid", "hagridden" ],
	[ "handwrite", "handwrites", "handwriting", "handwrote", "handwritten" ],
	[ "heatsink", "heatsinks", "heatsinking", "heatsinked", "heatsunk" ],
	[ "heave", "heaves", "heaving", "heaved", "hove", "hove", "hoven" ],
	[ "hele", "heles", "heling", "hole", "heled", "holen" ],
	[ "help", "helps", "helping", "helped" ],
	[ "hew", "hews", "hewing", "hewed", "hewn" ],
	[ "hold", "holds", "holding", "held" ],
	[ "hote", "hotes", "hoting", "hight", "hoten" ],
	[ "hould", "houlds", "houlding" ],
	[ "housebreak", "housebreaks", "housebreaking", "housebroke", "housebroken" ],
	[ "inbear", "inbears", "inbearing", "inbore", "inborne" ],
	[ "inbeat", "inbeats", "inbeating", "inbeat", "inbeaten" ],
	[ "inblow", "inblows", "inblowing", "inblew", "inblown" ],
	[ "inbreak", "inbreaks", "inbreaking", "inbroke", "inbroken" ],
	[ "indelve", "indelves", "indelving", "indelved", "indolve", "indolven" ],
	[ "infall", "infalls", "infalling", "infell", "infallen" ],
	[ "ingrow", "ingrows", "ingowing", "ingrew", "ingrown" ],
	[ "inhold", "inholds", "inholding", "inheld", "inheld", "inholden" ],
	[ "insee", "insees", "inseeing", "insaw", "inseen" ],
	[ "instrew", "instrews", "instrewing", "instrewed", "instrewn" ],
	[ "intercome", "intercomes", "intercoming", "intercame" ],
	[ "intergrow", "intergrows", "intergrowing", "intergrew", "intergrown" ],
	[ "interknow", "interknows", "interknowing", "interknew", "interknown" ],
	[ "interweave", "interweaves", "interweaving", "interwove", "interweaved", "interwoven" ],
	[ "inweave", "inweaves", "inweaving", "inwove", "inwoven" ],
	[ "inwrite", "inwrites", "inwriting", "inwrote", "inwritten" ],
	[ "jailbreak", "jailbreaks", "jailbreaking", "jailbroke", "jailbroken" ],
	[ "jigsaw", "jigsaws", "jigsawing", "jigsawed", "jigsawed", "jigsawn" ],
	[ "joyride", "joyrides", "joyriding", "joyrode", "joyridden" ],
	[ "know", "knows", "knowing", "knew", "known" ],
	[ "lade", "lades", "lading", "laded", "laden" ],
	[ "leap", "leaps", "leaping", "leaped", "leapt" ],
	[ "learn", "learns", "learning", "learned", "learnt" ],
	[ "lemme" ],
	[ "let", "lets", "letting", "letten" ],
	[ "lin", "lins", "linning", "linned", "lan", "linned", "lun" ],
	[ "manswear", "manswears", "manswearing", "manswore", "mansworn" ],
	[ "melt", "melts", "melting", "melted", "molt" ],
	[ "mis-hit", "mis-hits", "mis-hits", "mis-hitting" ],
	[ "misbear", "misbears", "misbearing", "misbore", "misborne" ],
	[ "misbeat", "misbeats", "misbeating", "misbeat", "misbeaten" ],
	[ "misbede", "misbedes", "misbeding", "misbode", "misboden" ],
	[ "misbefall", "misbefalls", "misbefalling", "misbefell", "misbefallen" ],
	[ "misbid", "misbids", "misbidding", "misbid", "misbad", "misbade", "misbidden" ],
	[ "mischoose", "mischooses", "mischoosing", "mischose", "mischosen" ],
	[ "miscleave", "miscleaves", "miscleaving", "miscleft", "misclove", "miscleaved", "miscloven" ],
	[ "miscome", "miscomes", "miscoming", "miscame" ],
	[ "misdo", "misdoes", "misdoing", "misdid", "misdone" ],
	[ "misfall", "misfalls", "misfalling", "misfell", "misfallen" ],
	[ "misget", "misgets", "misgetting", "misgot", "misgotten" ],
	[ "misgive", "misgives", "misgiving", "misgave", "misgiven" ],
	[ "misgo", "misgoes", "misgoing", "miswent", "misgone" ],
	[ "misgrow", "misgrows", "misgrowing", "misgrew", "misgrown" ],
	[ "mishold", "misholds", "misholding", "misheld", "misholden" ],
	[ "misknow", "misknows", "misknowing", "misknew", "misknown" ],
	[ "mislie", "mislies", "mislying", "mislay", "mislain" ],
	[ "missee", "missees", "misseeing", "missaw", "misseen" ],
	[ "misspeak", "misspeaks", "misspeaking", "misspoke", "misspoken" ],
	[ "misswear", "misswears", "misswearing", "misswore", "missworn" ],
	[ "mistake", "mistakes", "mistaking", "mistook", "mistaken" ],
	[ "misthrow", "misthrows", "misthrowing", "misthrew", "misthrown" ],
	[ "miswear", "miswears", "miswearing", "miswore", "misworn" ],
	[ "miswrite", "miswrites", "miswriting", "miswrote", "miswritten" ],
	[ "misyield", "misyields", "misyielding", "misyielded", "misyold", "misyolden" ],
	[ "nill", "nills", "nilling", "nilled", "nould" ],
	[ "nim", "nims", "nimming", "nimmed", "nam", "nimmed", "numb", "nomen", "num" ],
	[ "noseride", "noserides", "noseriding", "noserode", "noseridden" ],
	[ "off-bear", "off-bears", "off-bearing", "off-bore", "off-borne" ],
	[ "offbear", "offbears", "offbearing", "offbore" ],
	[ "offhold", "offholds", "offholding", "offheld", "offheld", "offholden" ],
	[ "offsmite", "offsmites", "offsmiting", "offsmote", "offsmitten" ],
	[ "offtake", "offtakes", "offtaking", "offtook", "offtaken" ],
	[ "oncome", "oncomes", "oncoming", "oncame" ],
	[ "onfall", "onfalls", "onfalling", "onfell", "onfallen" ],
	[ "onhold", "onholds", "onholding", "onheld", "onholden" ],
	[ "ontake", "ontakes", "ontaking", "ontook", "ontaken" ],
	[ "ought", "oughts" ],
	[ "outbear", "outbears", "outbearing", "outbore", "outborne" ],
	[ "outbreak", "outbreaks", "outbreaking", "outbroke", "outbroken" ],
	[ "outburst", "outbursts", "outbursting", "outburst", "outbrast", "outbursten" ],
	[ "outcreep", "outcreeps", "outcreeping", "outcrept", "outcrope", "outcropen" ],
	[ "outdo", "outdoes", "outdoing", "outdid", "outdone" ],
	[ "outdraw", "outdraws", "outdrawing", "outdrew", "outdrawn" ],
	[ "outdrive", "outdrives", "outdriving", "outdrove", "outdriven" ],
	[ "outeat", "outeats", "outeating", "outate", "outeaten" ],
	[ "outfall", "outfalls", "outfalling", "outfell", "outfallen" ],
	[ "outfly", "outflies", "outflying", "outflew", "outflown" ],
	[ "outgive", "outgives", "outgiving", "outgave", "outgiven" ],
	[ "outgo", "outgoes", "outgoing", "outwent", "outgone" ],
	[ "outgrow", "outgrows", "outgrowing", "outgrew", "outgrown" ],
	[ "outhold", "outholds", "outholding", "outheld", "outholden" ],
	[ "outnim", "outnims", "outnimming", "outnam", "outnimmed", "outnome", "outnomen", "outnum" ],
	[ "outride", "outrides", "outriding", "outrode", "outridden" ],
	[ "outring", "outrings", "outringing", "outrang", "outrung" ],
	[ "outrive", "outrives", "outriving", "outrove", "outriven" ],
	[ "outrun", "outruns", "outrunning", "outran", "outrun" ],
	[ "outsee", "outsees", "outseeing", "outsaw", "outseen" ],
	[ "outshow", "outshows", "outshowing", "outshowed", "outshown" ],
	[ "outsing", "outsings", "outsinging", "outsang", "outsung" ],
	[ "outspeak", "outspeaks", "outspeaking", "outspoke", "outspoken" ],
	[ "outspring", "outsprings", "outspringing", "outsprang", "outsprung" ],
	[ "outstink", "outstinks", "outstinking", "outstank", "outstunk" ],
	[ "outstrike", "outstrikes", "outstriking", "outstruck", "outstricken" ],
	[ "outswear", "outswears", "outswearing", "outswore", "outsworn" ],
	[ "outswell", "outswells", "outswelling", "outswelled", "outswollen" ],
	[ "outswim", "outswims", "outswimming", "outswam", "outswum" ],
	[ "outtake", "outtakes", "outtaking", "outtook", "outtaken" ],
	[ "outthrow", "outthrows", "outthrowing", "outthrew", "outthrown" ],
	[ "outwear", "outwears", "outwearing", "outwore", "outworn" ],
	[ "outwrite", "outwrites", "outwriting", "outwrote", "outwritten" ],
	[ "overbear", "overbears", "overbearing", "overbore", "overborne" ],
	[ "overbeat", "overbeats", "overbeating", "overbeat", "overbeaten" ],
	[ "overbide", "overbides", "overbiding", "overbode", "overbided" ],
	[ "overblow", "overblows", "overblowing", "overblew", "overblown" ],
	[ "overbreak", "overbreaks", "overbreaking", "overbroke", "overbroken" ],
	[ "overcarve", "overcarves", "overcarving", "overcarved", "overcorve" ],
	[ "overcome", "overcomes", "overcoming", "overcame" ],
	[ "overdo", "overdoes", "overdoing", "overdid", "overdone" ],
	[ "overdraw", "overdraws", "overdrawing", "overdrew", "overdrawn" ],
	[ "overdrink", "overdrinks", "overdrinking", "overdrank", "overdrunk" ],
	[ "overdrive", "overdrives", "overdriving", "overdrove", "overdriven" ],
	[ "overeat", "overeats", "overeating", "overate", "overeaten" ],
	[ "overfall", "overfalls", "overfalling", "overfell", "overfallen" ],
	[ "overfly", "overflies", "overflying", "overflew", "overflown" ],
	[ "overget", "overgets", "overgetting", "overgot", "overgat", "overgotten" ],
	[ "overgive", "overgives", "overgiving", "overgave", "overgiven" ],
	[ "overgo", "overgoes", "overgoing", "overwent", "overgone" ],
	[ "overgrow", "overgrows", "overgrowing", "overgrew", "overgrown" ],
	[ "overheave", "overheaves", "overheaving", "overhove", "overheaved", "overhoven" ],
	[ "overhold", "overholds", "overholding", "overheld", "overholden" ],
	[ "overlade", "overlades", "overlading", "overladed" ],
	[ "overlie", "overlies", "overlying", "overlay", "overlain" ],
	[ "override", "overrides", "overriding", "overrode", "overridden" ],
	[ "overrun", "overruns", "overrunning", "overran", "overrun" ],
	[ "oversee", "oversees", "overseeing", "oversaw", "overseen" ],
	[ "overshake", "overshakes", "overshaking", "overshook", "overshaken" ],
	[ "oversow", "oversows", "oversowing", "oversowed", "oversown" ],
	[ "overspeak", "overspeaks", "overspeaking", "overspoke", "overspoken" ],
	[ "overspring", "oversprings", "overspringing", "oversprang", "oversprung" ],
	[ "overstraw", "overstraws", "overstrawing", "overstrawed", "overstrawn" ],
	[ "overstrew", "overstrews", "overstrewing", "overstrewed", "overstrewn" ],
	[ "overstrow", "overstrows", "overstrowing", "overstrowed", "overstrown" ],
	[ "overtake", "overtakes", "overtaking", "overtook", "overtaken" ],
	[ "overthrow", "overthrows", "overthrowing", "overthrew", "overthrown" ],
	[ "overtread", "overtreads", "overtreading", "overtrod", "overtrodden" ],
	[ "overwear", "overwears", "overwearing", "overwore", "overworn" ],
	[ "overwrite", "overwrites", "overwriting", "overwrote", "overwritten" ],
	[ "partake", "partakes", "partaking", "partook", "partaken" ],
	[ "pay", "pays", "paying", "paid" ],
	[ "phoneticize", "phoneticizes", "phoneticizing", "phoneticized" ],
	[ "pig-out", "pigs-out", "pigging-out", "pigged-out" ],
	[ "piledrive", "piledrives", "piledriving", "piledrove", "piledriven" ],
	[ "prank", "pranks", "pranking", "pranked", "prankt" ],
	[ "pratfall", "pratfalls", "pratfalling", "pratfell", "pratfallen" ],
	[ "precum", "precums", "precumming", "precame", "precummed" ],
	[ "prepay", "prepays", "prepaying", "prepaid", "prepayed" ],
	[ "prerun", "preruns", "prerunning", "preran", "prerun" ],
	[ "presew", "presews", "presewing", "presewed", "presewn" ],
	[ "preshow", "preshows", "preshowing", "preshowed", "preshown" ],
	[ "preshrink", "preshrinks", "preshrinking", "preshrank", "preshrunk", "preshrunken" ],
	[ "prewrite", "prewrites", "prewriting", "prewrote", "prewritten" ],
	[ "proove", "prooves", "prooving", "prooved", "prooven" ],
	[ "prove", "proves", "proving", "proved", "proven" ],
	[ "quartersaw", "quartersaws", "quartersawing", "quartersawed", "quartersawn" ],
	[ "quethe", "quethes", "quething", "quethed", "quod", "quoth", "quethen" ],
	[ "quick-freeze", "quick-freezes", "quick-freezing", "quick-froze", "quick-frozen" ],
	[ "re-run", "re-runs", "re-running", "re-ran", "re-run" ],
	[ "re-sew", "re-sews", "re-sewing", "re-sewed", "re-sewn" ],
	[ "read", "reads", "reading", "read", "read" ],
	[ "reawake", "reawakes", "reawaking", "reawoke", "reawaked", "reawoken" ],
	[ "rebear", "rebears", "rebearing", "rebore", "reborne" ],
	[ "rebecome", "rebecomes", "rebecoming", "rebecame" ],
	[ "rebegin", "rebegins", "rebeginning", "rebegan", "rebegun" ],
	[ "rebreak", "rebreaks", "rebreaking", "rebroke", "rebroken" ],
	[ "rechoose", "rechooses", "rechoosing", "rechose", "rechosen" ],
	[ "redo", "redoes", "redoing", "redid", "redone" ],
	[ "redraw", "redraws", "redrawing", "redrew", "redrawn" ],
	[ "refall", "refalls", "refalling", "refell", "refallen" ],
	[ "refly", "reflies", "reflying", "reflew", "reflown" ],
	[ "refreeze", "refreezes", "refreezing", "refroze", "refrozen" ],
	[ "regive", "regives", "regiving", "regave", "regiven" ],
	[ "regrow", "regrows", "regrowing", "regrew", "regrown" ],
	[ "rehew", "rehews", "rehewing", "rehewed", "rehewn" ],
	[ "rehide", "rehides", "rehiding", "rehid", "rehidden" ],
	[ "rerun", "reruns", "rerunning", "reran" ],
	[ "resee", "resees", "reseeing", "resaw", "reseen", "resaws", "resawing", "resawed", "resawn" ],
	[ "resew", "resews", "resewing", "resewed", "resewn" ],
	[ "reshake", "reshakes", "reshaking", "reshook", "reshaken" ],
	[ "resow", "resows", "resowing", "resowed", "resown" ],
	[ "respeak", "respeaks", "respeaking", "respoke", "respoken" ],
	[ "restrike", "restrikes", "restriking", "restruck", "restricken" ],
	[ "restrive", "restrives", "restriving", "restrove", "restriven" ],
	[ "reswear", "reswears", "reswearing", "reswore" ],
	[ "retake", "retakes", "retaking", "retook", "retaken" ],
	[ "retear", "retears", "retearing", "retore", "retorn" ],
	[ "rethrow", "rethrows", "rethrowing", "rethrew", "rethrown" ],
	[ "rewake", "rewakes", "rewaking", "rewoke", "rewoken)" ],
	[ "reweave", "reweaves", "reweaving", "rewove", "rewoven" ],
	[ "rewrite", "rewrites", "rewriting", "rewrote", "rewritten" ],
	[ "rid", "rids", "ridding", "rid", "ridded" ],
	[ "ride", "rides", "riding", "rode", "ridden" ],
	[ "rise", "rises", "rising", "rose", "risen" ],
	[ "rive", "rives", "riving", "rived", "rove" ],
	[ "roadshow", "roadshows", "roadshowing", "roadshowed", "roadshown" ],
	[ "rough-hew", "rough-hews", "rough-hewing", "rough-hewed", "rough-hewn" ],
	[ "roughhew", "roughhews", "roughhewing", "roughhewed", "roughhewed", "roughhewn" ],
	[ "run", "runs", "running", "ran", "rin", "rins", "rinning" ],
	[ "satanize", "satanizes", "satanizing", "satanized"  ],
	[ "see", "sees", "seeing", "saw", "seen", "saws", "sawing", "sawed", "sawn" ],
	[ "seethe", "seethes", "seething", "seethed", "sod", "sodden" ],
	[ "set", "sets", "setting" ],
	[ "shake", "shakes", "shaking", "shook", "shaken" ],
	[ "shall", "should" ],
	[ "shape", "shapes", "shaping", "shaped", "shapen" ],
	[ "shave", "shaves", "shaving", "shaved", "shaven" ],
	[ "shear", "shears", "shearing", "sheared", "shore", "shorn" ],
	[ "shew", "shews", "shewing", "shewed", "shewn" ],
	[ "shit", "shits", "shitting", "shit", "shat", "shitted", "shit", "shitten" ],
	[ "shoe", "shoes", "shoeing", "shod", "shoed", "shodden" ],
	[ "shoot", "shoots", "shooting", "shot", "shotten" ],
	[ "show", "shows", "showing", "showed", "shown" ],
	[ "showrun", "showruns", "showrunning", "showran" ],
	[ "shred", "shreds", "shredding", "shredded", "shred" ],
	[ "shrieve", "shrieves", "shrieving", "shrieved", "shriven", "shrive", "shrives", "shriving", "shrived", "shrove", "shrived" ],
	[ "shrink", "shrinks", "shrinking", "shrank", "shrunk", "shrunken" ],
	[ "sightsee", "sightsees", "sightseeing", "sightsaw", "sightseen" ],
	[ "sing", "sings", "singing", "sang", "sung" ],
	[ "sink", "sinks", "sinking", "sank", "sunk", "sunken" ],
	[ "sit", "sits", "sitting", "sat", "sitten" ],
	[ "slay", "slays", "slaying", "slew", "slayed", "slain" ],
	[ "sling", "slings", "slinging", "slung", "slang" ],
	[ "slingshoot", "slingshoots", "slingshooting", "slingshot", "slingshotten" ],
	[ "slit", "slits", "slitting", "slitten", "slite", "slites", "sliting", "slote", "slited", "slited" ],
	[ "smart", "smarts", "smarting", "smarted" ],
	[ "smite", "smites", "smiting", "smote", "smitten", "smited" ],
	[ "sneeze", "sneezes", "sneezing", "sneezed", "snoze", "snozen" ],
	[ "snow", "snows", "snowing", "snowed", "snew", "snown" ],
	[ "solo" ,"soloes", "soloing", "soloed" ],
	[ "sow", "sows", "sowing", "sowed", "sown" ],
	[ "speak", "speaks", "speaking", "spoke", "spoken" ],
	[ "speedrun", "speedruns", "speedrunning", "speedran", "speedrun" ],
	[ "spin", "spins", "spinning", "spun", "spun" ],
	[ "spring", "springs", "springing", "sprang", "sprung" ],
	[ "sprint", "sprints", "sprinting", "sprinted", "sprinted", "sprunt" ],
	[ "starve", "starves", "starving", "starved", "starf", "storven" ],
	[ "steal", "steals", "stealing", "stole", "stolen" ],
	[ "step", "steps", "stepping", "stepped", "stept", "stopen" ],
	[ "sting", "stings", "stinging", "stung", "stang" ],
	[ "stink", "stinks", "stinking", "stank", "stunk" ],
	[ "strew", "strews", "strewing", "strewed", "strewn", "strewed" ],
	[ "stride", "strides", "striding", "strode", "stridden", "strid" ],
	[ "strike", "strikes", "striking", "struck", "struck", "stricken" ],
	[ "strikethrough", "strikethroughs", "strikingthrough", "struckthrough", "strickenthrough" ],
	[ "strive", "strives", "striving", "strove", "strived", "striven" ],
	[ "strow", "strows", "strowing", "strowed", "strown" ],
	[ "superlie", "superlies", "superlying", "superlay", "superlain" ],
	[ "surbeat", "surbeats", "surbeating", "surbeated", "surbeaten" ],
	[ "sweare", "sweares", "swearing", "swore", "sworne" ],
	[ "swell", "swells", "swelling", "swelled", "swollen" ],
	[ "swike", "swikes", "swiking", "swoke", "swicken" ],
	[ "swim", "swims", "swimming", "swam", "swum" ],
	[ "swing", "swings", "swinging", "swang", "swung", "swung", "swungen" ],
	[ "swink", "swinks", "swinking", "swank", "swonk", "swinkt", "swunk", "swinked", "swunken", "swonken" ],
	[ "take", "takes", "taking", "took", "taken" ],
	[ "talebear", "talebears", "talebearing", "talebore", "taleborne" ],
	[ "tattoo", "tattooes", "tattooing", "tattooed", "tattoed" ],
	[ "teach", "teaches", "teaching", "taught" ],
	[ "test-drive", "test-drives", "test-driving", "test-drove", "test-driven" ],
	[ "test-fly", "test-flies", "test-flying", "test-flew", "test-flown" ],
	[ "thanksgive", "thanksgives", "thanksgiving", "thanksgave", "thanksgiven" ],
	[ "tharf", "tharfs", "thurving", "tharving", "thurft", "tharved" ],
	[ "thoroughgo", "thoroughgoes", "thoroughgoing", "thoroughwent", "thoroughgone" ],
	[ "thread", "threads", "threading", "threaded,", "thrid", "thridden" ],
	[ "thring", "thrings", "thringing", "thrang", "thrung" ],
	[ "thrive", "thrives", "thriving", "throve", "thrived", "thriven" ],
	[ "throw", "throws", "throwing", "threw", "thrown" ],
	[ "thunderstrike", "thunderstrikes", "thunderstriking", "thunderstruck", "thunderstricken" ],
	[ "tobeat", "tobeats", "tobeating", "tobeat", "tobeaten" ],
	[ "tobreak", "tobreaks", "tobreaking", "tobroke", "tobroken" ],
	[ "toburst", "tobursts", "tobursting", "toburst", "tobursten" ],
	[ "tocleave", "tocleaves", "tocleaving", "toclove", "tocleaved", "tocleft", "tocloven" ],
	[ "todraw", "todraws", "todrawing", "todrew", "todrawn" ],
	[ "todrive", "todrives", "todriving", "todrove", "todriven" ],
	[ "togo", "togoes", "togoing", "towent", "togone" ],
	[ "tohew", "tohews", "tohewing", "tohewed", "tohewn" ],
	[ "tole", "toles", "toling", "toled", "toled", "tollen" ],
	[ "toshake", "toshakes", "toshaking", "toshook", "toshaken" ],
	[ "toshear", "toshears", "toshearing", "toshore", "toshorn" ],
	[ "toswink", "toswinks", "toswinking", "toswank", "toswunk", "toswunken" ],
	[ "totear", "totears", "totearing", "totore", "totorn" ],
	[ "totread", "totreads", "totreading", "totrod", "totrodden" ],
	[ "tweet", "tweets", "tweeting", "tweeted", "twote", "tweeted", "twoten" ],
	[ "typewrite", "typewrites", "typewriting", "typewrote", "typewritten" ],
	[ "umbedraw", "umbedraws", "umbedrawing", "umbedrew", "umbedrawn" ],
	[ "umbego", "umbegoes", "umbegoing", "umbewent", "umbegone" ],
	[ "umbeset", "umbesets", "umbesetting", "umbesetten" ],
	[ "un-break", "un-breaks", "un-breaking", "un-broke", "un-broken" ],
	[ "unbear", "unbears", "unbearing", "unbore", "unborne" ],
	[ "unbecome", "unbecomes", "unbecoming", "unbecame" ],
	[ "unbespeak", "unbespeaks", "unbespeaking", "unbespoke", "unbespoken" ],
	[ "unbid", "unbids", "unbidding", "unbid", "unbid", "unbidden" ],
	[ "unbind", "unbinds", "unbinding", "unbound", "unbound", "unbounden" ],
	[ "unbreak", "unbreaks", "unbreaking", "unbroke", "unbroken" ],
	[ "unchoose", "unchooses", "unchoosing", "unchose", "unchosen" ],
	[ "underbear", "underbears", "underbearing", "underbore,", "underbare", "underborne" ],
	[ "undercome", "undercomes", "undercoming", "undercame" ],
	[ "undercreep", "undercreeps", "undercreeping", "undercrept", "undercrope", "undercropen" ],
	[ "underdelve", "underdelves", "underdelving", "underdelved", "underdolve", "underdolven" ],
	[ "underdo", "underdoes", "underdoing", "underdid", "underdone" ],
	[ "underdraw", "underdraws", "underdrawing", "underdrew", "underdrawn" ],
	[ "undereat", "undereats", "undereating", "underate", "undereaten" ],
	[ "underget", "undergets", "undergetting", "undergot", "undergotten" ],
	[ "undergo", "undergoe", "undergoes", "undergoing", "underwent", "undergone" ],
	[ "undergrow", "undergrows", "undergrowing", "undergrew", "undergrown" ],
	[ "underhold", "underholds", "underholding", "underheld", "underheld", "underholden" ],
	[ "underlie", "underly", "underlies", "underlying", "underlay", "underlain" ],
	[ "undernim", "undernims", "undernimming", "undernimmed", "undernam", "undernimmed", "undernomen", "undernum", "undernome" ],
	[ "underrun", "underruns", "underrunning", "underran" ],
	[ "undersee", "undersees", "underseeing", "undersaw", "underseen" ],
	[ "undersow", "undersows", "undersowing", "undersowed", "undersown" ],
	[ "undertake", "undertakes", "undertaking", "undertook", "undertaken" ],
	[ "underthrow", "underthrows", "underthrowing", "underthrew", "underthrown" ],
	[ "underwrite", "underwrites", "underwriting", "underwrote", "underwritten" ],
	[ "undo", "undoes", "undoing", "undid", "undone" ],
	[ "undraw", "undraws", "undrawing", "undrew", "undrawn" ],
	[ "unfreeze", "unfreezes", "unfreezing", "unfroze", "unfrozen" ],
	[ "ungive", "ungives", "ungiving", "ungave", "ungiven" ],
	[ "unhelp", "unhelps", "unhelping", "unholp", "unhelped", "unholpen" ],
	[ "unhide", "unhides", "unhiding", "unhid", "unhidden" ],
	[ "unknow", "unknows", "unknowing", "unknew", "unknown" ],
	[ "unlade", "unlades", "unlading", "unladed" ],
	[ "unsee", "unsees", "unseeing", "unsaw", "unseen" ],
	[ "unsew", "unsews", "unsewing", "unsewed", "unsewn" ],
	[ "unshape", "unshapes", "unshaping", "unshaped", "unshope", "unshapen" ],
	[ "unspeak", "unspeaks", "unspeaking", "unspoke", "unspoken" ],
	[ "unswear", "unswears", "unswearing", "unswore", "unsworn" ],
	[ "unswell", "unswells", "unswelling", "unswelled", "unswollen" ],
	[ "unweave", "unweaves", "unweaving", "unwove", "unwoven" ],
	[ "unwrite", "unwrites", "unwriting", "unwrote", "unwritten" ],
	[ "upbear", "upbears", "upbearing", "upbore", "upborne" ],
	[ "upblow", "upblows", "upblowing", "upblew", "upblown" ],
	[ "upbreak", "upbreaks", "upbreaking", "upbroke", "upbroken" ],
	[ "upcome", "upcomes", "upcoming", "upcame", "upcome" ],
	[ "updraw", "updraws", "updrawing", "updrew", "updrawn" ],
	[ "upgive", "upgives", "upgiving", "upgave", "upgiven" ],
	[ "upgrow", "upgrows", "upgrowing", "upgrew", "upgrown" ],
	[ "upheave", "upheaves", "upheaving", "upheaved", "uphove", "uphoven" ],
	[ "uphold", "upholds", "upholding", "upheld", "upholden" ],
	[ "upleap", "upleaps", "upleaping", "upleaped", "uplept", "upleapt", "uplope", "uplopen" ],
	[ "uprise", "uprises", "uprising", "uprose", "uprisen" ],
	[ "uprun", "upruns", "uprunning", "upran" ],
	[ "upspeak", "upspeaks", "upspeaking", "upspoke", "upspoken" ],
	[ "upspring", "upsprings", "upspringing", "upsprang", "upsprung", ")" ],
	[ "upswell", "upswells", "upswelling", "upswelled", "upswelled", "upswollen" ],
	[ "uptear", "uptears", "uptearing", "uptore", "uptorn" ],
	[ "upthrow", "upthrows", "upthrowing", "upthrew", "upthrown" ],
	[ "wake", "wakes", "waking", "woke", "waked", "woken" ],
	[ "war-drive", "war-drives", "war-driving", "war-drove", "war-driven" ],
	[ "wardrive", "wardrives", "wardriving", "wardrove", "wardriven" ],
	[ "wayfare", "wayfares", "wayfaring", "wayfore", "wayfared", "wayfaren" ],
	[ "wear", "wears", "wearing", "weared", "wore", "weared", "worn" ],
	[ "will", "wills", "willing", "willed" ],
	[ "win", "wins", "winning", "won" ],
	[ "wind-break", "wind-breaks", "wind-breaking", "wind-broke", "wind-broken" ],
	[ "wiredraw", "wiredraws", "wiredrawing", "wiredrew", "wiredrawn" ],
	[ "wis", "wiss", "wist", "wissed" ],
	[ "withbear", "withbears", "withbearing", "withbore", "withborne" ],
	[ "withdraw", "withdraws", "withdrawing", "withdrew", "withdrawn" ],
	[ "withdrive", "withdrives", "withdriving", "withdrove", "withdriven" ],
	[ "withgo", "withgoes", "withgoing", "withwent", "withgone" ],
	[ "withhold", "withholds", "withholding", "withheld", "withheld", "withholden" ],
	[ "withsake", "withsakes", "withsaking", "withsook", "withsaken" ],
	[ "withsit", "withsits", "withsitting", "withsat", "withsat", "withsitten" ],
	[ "withspeak", "withspeaks", "withspeaking", "withspoke", "withspoken" ],
	[ "withtake", "withtakes", "withtaking", "withtook", "withtaken" ],
	[ "worth", "worths", "worthing", "worth", "worthed", "worthen" ],
	[ "wreak", "wreaks", "wreaking", "wreaked", "wroke", "wroken", "wrought" ],
	[ "wring", "wrings", "wringing", "wrang", "wrung", "wringed" ],
	[ "write", "writes", "writing", "wrote", "written", "writ" ],
	[ "write-off", "write-offs", "writing-off", "wrote-off", "written-off" ],
	[ "writhe", "writhes", "writhing", "writhed", "wrothe", "writhen" ],
	[ "yield", "yields", "yielding", "yielded", "yolden" ],
	[ "yive", "yives", "yiving", "yave", "yiven" ],
	[ "die", "dies", "dying", "died" ],
	[ "lie", "lies", "lying", "lain", "lied" ],
	[ "tie", "ties", "tying", "tied" ],
	[ "vie", "vies", "vying", "vied" ],
	[ "confer", "confers", "conferring", "conferred" ],
	[ "defer", "defers", "deferring", "deferred" ],
	[ "refer", "refers", "referring", "referred" ],
	[ "occur", "occurs", "occurring", "occurred" ],
	[ "catch", "catches", "catching", "caught" ],
];
