# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  JavaScript: true
  PHP: true
exclude_paths:
- "tests/*"
- "grunt/*"
- "grunt/**/*"
- "inc/wpseo-functions-deprecated.php"
- "js/dist/*"