<?php

// phpcs:disable Yoast.NamingConventions.NamespaceName.TooLong
namespace Yoast\WP\SEO\Llms_Txt\Application\Markdown_Builders;

use Yoast\WP\SEO\Llms_Txt\Domain\Markdown\Sections\Intro;
use Yoast\WP\SEO\Llms_Txt\Infrastructure\Markdown_Services\Sitemap_Link_Collector;

/**
 * The builder of the intro section.
 */
class Intro_Builder {

	/**
	 * The sitemap link collector.
	 *
	 * @var Sitemap_Link_Collector
	 */
	protected $sitemap_link_collector;

	/**
	 * The constructor.
	 *
	 * @param Sitemap_Link_Collector $sitemap_link_collector The sitemap link collector.
	 */
	public function __construct(
		Sitemap_Link_Collector $sitemap_link_collector
	) {
		$this->sitemap_link_collector = $sitemap_link_collector;
	}

	/**
	 * Builds the intro section.
	 *
	 * @return Intro The intro section.
	 */
	public function build_intro(): Intro {
		$intro_content = 'Generated by Yoast SEO, this is an llms.txt file, meant for consumption by LLMs.';

		$sitemap_link = $this->sitemap_link_collector->get_link();
		if ( $sitemap_link !== null ) {
			$intro_content .= \PHP_EOL . \PHP_EOL;
			$intro_content .= \sprintf(
				'This is the %s of this website.',
				$sitemap_link->render()
			);
		}

		return new Intro( $intro_content );
	}
}
