<?php

namespace Yoast\WP\SEO\Tests\Unit\Integrations;

use Brain\Monkey\Filters;
use Brain\Monkey\Functions;
use Mockery;
use WP_REST_Request;
use Yoast\WP\SEO\Integrations\Primary_Category_REST;
use Yoast\WP\SEO\Tests\Unit\TestCase;

/**
 * Class Primary_Category_REST_Test.
 *
 * @coversDefaultClass \Yoast\WP\SEO\Integrations\Primary_Category_REST
 *
 * @group integrations
 */
final class Primary_Category_REST_Test extends TestCase {

	/**
	 * Holds the instance of the class being tested.
	 *
	 * @var Primary_Category_REST
	 */
	protected $instance;

	/**
	 * Sets up the class under test.
	 *
	 * @return void
	 */
	protected function set_up() {
		parent::set_up();

		$this->instance = new Primary_Category_REST();
	}

	/**
	 * Tests that the integration has no conditionals.
	 *
	 * @covers ::get_conditionals
	 *
	 * @return void
	 */
	public function test_get_conditionals() {
		$this->assertEquals( [], Primary_Category_REST::get_conditionals() );
	}

	/**
	 * Tests that the REST filters are registered.
	 *
	 * @covers ::register_hooks
	 *
	 * @return void
	 */
	public function test_register_hooks() {
		Filters\expectAdded( 'rest_post_collection_params' )
			->once()
			->with( [ $this->instance, 'add_collection_param' ], 10, 2 );
		Filters\expectAdded( 'rest_post_query' )
			->once()
			->with( [ $this->instance, 'filter_post_query' ], 10, 2 );

		$this->instance->register_hooks();
	}

	/**
	 * Tests that the collection parameter is added for the post post type.
	 *
	 * @covers ::add_collection_param
	 *
	 * @return void
	 */
	public function test_add_collection_param_for_posts() {
		Functions\when( '__' )->justReturn( 'Limit result set to posts with a specific primary category.' );

		$params     = [
			'per_page' => [
				'type'    => 'integer',
				'default' => 10,
			],
		];
		$post_type  = (object) [ 'name' => 'post' ];
		$parameters = $this->instance->add_collection_param( $params, $post_type );

		$this->assertArrayHasKey( 'primary_category', $parameters );
		$this->assertSame( 'integer', $parameters['primary_category']['type'] );
		$this->assertSame( 1, $parameters['primary_category']['minimum'] );
		$this->assertSame( 'absint', $parameters['primary_category']['sanitize_callback'] );
		$this->assertArrayHasKey( 'per_page', $parameters );
	}

	/**
	 * Tests that the collection parameter is not added for other post types.
	 *
	 * @dataProvider other_post_types_provider
	 *
	 * @covers ::add_collection_param
	 *
	 * @param string $post_type_name The post type name.
	 *
	 * @return void
	 */
	public function test_add_collection_param_for_other_post_types( $post_type_name ) {
		$params    = [
			'per_page' => [
				'type'    => 'integer',
				'default' => 10,
			],
		];
		$post_type = (object) [ 'name' => $post_type_name ];

		$this->assertSame( $params, $this->instance->add_collection_param( $params, $post_type ) );
	}

	/**
	 * Provides post types other than post.
	 *
	 * @return array<array<string>> The test data.
	 */
	public static function other_post_types_provider() {
		return [
			[ 'page' ],
			[ 'product' ],
		];
	}

	/**
	 * Tests that the primary category is queried exactly.
	 *
	 * @covers ::filter_post_query
	 *
	 * @return void
	 */
	public function test_filter_post_query() {
		Functions\when( 'absint' )->alias(
			static function ( $value ) {
				return \abs( (int) $value );
			},
		);

		$request = Mockery::mock( WP_REST_Request::class );
		$request->expects( 'get_param' )->with( 'primary_category' )->once()->andReturn( '123' );

		$actual = $this->instance->filter_post_query( [], $request );

		$expected = [
			// phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_query -- Mirrors the query generated by the integration.
			'meta_query' => [
				[
					'key'     => '_yoast_wpseo_primary_category',
					'value'   => 123,
					'type'    => 'numeric',
					'compare' => '=',
				],
			],
			// phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_tax_query -- Mirrors the query generated by the integration.
			'tax_query'  => [
				[
					'taxonomy'         => 'category',
					'field'            => 'term_id',
					'terms'            => 123,
					'include_children' => false,
				],
			],
		];
		$this->assertSame( $expected, $actual );
	}

	/**
	 * Tests that an existing meta or tax query is not overwritten.
	 *
	 * @covers ::filter_post_query
	 *
	 * @return void
	 */
	public function test_filter_post_query_keeps_existing_queries() {
		Functions\when( 'absint' )->alias(
			static function ( $value ) {
				return \abs( (int) $value );
			},
		);

		$request = Mockery::mock( WP_REST_Request::class );
		$request->expects( 'get_param' )->with( 'primary_category' )->once()->andReturn( 5 );

		$args = [
			// phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_query -- Existing query fixture for merge behavior.
			'meta_query' => [
				[
					'key'     => 'existing_key',
					'value'   => 'existing_value',
					'compare' => '=',
				],
			],
			// phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_tax_query -- Existing query fixture for merge behavior.
			'tax_query'  => [
				[
					'taxonomy' => 'post_tag',
					'field'    => 'slug',
					'terms'    => [ 'tagged' ],
				],
			],
		];

		$actual = $this->instance->filter_post_query( $args, $request );

		$this->assertCount( 2, $actual['meta_query'] );
		$this->assertSame( 'existing_key', $actual['meta_query'][0]['key'] );
		$this->assertSame( '_yoast_wpseo_primary_category', $actual['meta_query'][1]['key'] );
		$this->assertCount( 2, $actual['tax_query'] );
		$this->assertSame( 'post_tag', $actual['tax_query'][0]['taxonomy'] );
		$this->assertSame( 'category', $actual['tax_query'][1]['taxonomy'] );
	}

	/**
	 * Tests that an invalid primary category is ignored.
	 *
	 * @covers ::filter_post_query
	 *
	 * @return void
	 */
	public function test_filter_post_query_without_primary_category() {
		Functions\when( 'absint' )->alias(
			static function ( $value ) {
				return \abs( (int) $value );
			},
		);

		$request = Mockery::mock( WP_REST_Request::class );
		$request->expects( 'get_param' )->with( 'primary_category' )->once()->andReturn( 'not-a-number' );

		$this->assertSame( [], $this->instance->filter_post_query( [], $request ) );
	}
}
