module.exports = [
	[ "good", "well", "better", "best" ],
	[ "red", "redder", "reddest" ],
	[ "tall", "taller", "tallest", "tally" ],
	[ "dull", "duller", "dullest", "dully" ],
	[ "bad", "badly", "worse", "worst" ],
	[ "far", "further", "father", "furthest", "farthest" ],
	[ "little", "less", "least" ],
	[ "many", "much", "more", "most" ],
	[ "bitter", "bitterer", "bitterest", "bitterly" ],
	[ "public", "publicly" ],
	[ "true", "truer", "truest", "truly" ],
	[ "fast", "faster", "fastest" ],
	[ "sole", "solely" ],
	[ "whole", "wholer", "wholest", "wholly" ],
	[ "full", "fuller", "fullest", "fully" ],
	[ "subtle", "subtler", "subtlest", "subtly" ],
	[ "gentle", "gentler", "gentlest", "gently" ],
	[ "simple", "simpler", "simplest", "simply" ],
	[ "full", "fuller", "fullest", "fully" ],
	[ "ample", "ampler", "amplest", "amply" ],
	[ "dumb", "dumber", "dumbest", "dumbly" ],
	[ "numb", "number", "numbest", "numbly" ],
	[ "early", "earlier", "earliest" ],
	[ "likely", "likelier", "likeliest" ],
	[ "daily", "dailier", "dailiest" ],
	[ "holy", "holier", "holiest" ],
	[ "friendly", "friendlier", "friendliest" ],
	[ "weekly", "weeklier", "weekliest" ],
	[ "lovely", "lovelier", "loveliest" ],
	[ "ugly", "uglier", "ugliest" ],
	[ "monthly", "monthlier", "monthliest" ],
	[ "deadly", "deadlier", "deadliest" ],
	[ "silly", "sillier", "silliest" ],
	[ "lonely", "lonelier", "loneliest" ],
	[ "costly", "costlier", "costliest" ],
	[ "lively", "livelier", "liveliest" ],
	[ "timely", "timelier", "timeliest" ],
	[ "chilly", "chillier", "chilliest" ],
	[ "curly", "curlier", "curliest" ],
	[ "nightly", "nightlier", "nightliest" ],
	[ "yearly", "yearlier", "yearliest" ],
	[ "sly", "slier", "sliest" ],
	[ "earthly", "earthlier", "earthliest" ],
	[ "worldly", "worldlier", "worldliest" ],
	[ "ghostly", "ghostlier", "ghostliest" ],
	[ "oily", "oilier", "oiliest" ],
	[ "stately", "statelier", "stateliest" ],
	[ "prickly", "pricklier", "prickliest" ],
	[ "hourly", "hourlier", "hourliest" ],
	[ "grizzly", "grizzlier", "grizzliest" ],
	[ "jolly", "jollier", "jolliest" ],
	[ "burly", "burlier", "burliest" ],
	[ "sickly", "sicklier", "sickliest" ],
	[ "bubbly", "bubblier", "bubbliest" ],
	[ "wobbly", "wobblier", "wobbliest" ],
	[ "manly", "manlier", "manliest" ],
	[ "ghastly", "ghastlier", "ghastliest" ],
	[ "steely", "steelier", "steeliest" ],
	[ "grisly", "grislier", "grisliest" ],
	[ "smelly", "smellier", "smelliest" ],
	[ "hilly", "hillier", "hilliest" ],
	[ "woolly", "woollier", "woolliest" ],
	[ "surly", "surlier", "surliest" ],
	[ "spindly", "spindlier", "spindliest" ],
	[ "homely", "homelier", "homeliest" ],
	[ "courtly", "courtlier", "courtliest" ],
	[ "priestly", "priestlier", "priestliest" ],
	[ "wily", "wilier", "wiliest" ],
	[ "pearly", "pearlier", "pearliest" ],
	[ "shapely", "shapelier", "shapeliest" ],
	[ "sparkly", "sparklier", "sparkliest" ],
	[ "deathly", "deathlier", "deathliest" ],
	[ "portly", "portlier", "portliest" ],
	[ "frilly", "frillier", "frilliest" ],
	[ "gangly", "ganglier", "gangliest" ],
	[ "crumbly", "crumblier", "crumbliest" ],
	[ "saintly", "saintlier", "saintliest" ],
	[ "scaly", "scalier", "scaliest" ],
	[ "godly", "godlier", "godliest" ],
	[ "princely", "princelier", "princeliest" ],
	[ "gravelly", "gravellier", "gravelliest" ],
	[ "scraggly", "scragglier", "scraggliest" ],
	[ "bristly", "bristlier", "bristliest" ],
	[ "girly", "girlier", "girliest" ],
	[ "comely", "comelier", "comeliest" ],
	[ "sprightly", "sprightlier", "sprightliest" ],
	[ "goodly", "goodlier", "goodliest" ],
	[ "beastly", "beastlier", "beastliest" ],
	[ "squiggly", "squigglier", "squiggliest" ],
	[ "crinkly", "crinklier", "crinkliest" ],
	[ "philly", "phillier", "philliest" ],
	[ "mealy", "mealier", "mealiest" ],
	[ "pebbly", "pebblier", "pebbliest" ],
	[ "wifely", "wifelier", "wifeliest" ],
	[ "lordly", "lordlier", "lordliest" ],
	[ "bluntly", "bluntlier", "bluntliest" ],
	[ "kingly", "kinglier", "kingliest" ],
	[ "wrinkly", "wrinklier", "wrinkliest" ],
	[ "wooly", "woolier", "wooliest" ],
	[ "drizzly", "drizzlier", "drizzliest" ],
	[ "stubbly", "stubblier", "stubbliest" ],
	[ "seely", "seelier", "seeliest" ],
	[ "pimply", "pimplier", "pimpliest" ],
	[ "wiggly", "wigglier", "wiggliest" ],
	[ "twinkly", "twinklier", "twinkliest" ],
	[ "knightly", "knightlier", "knightliest" ],
	[ "straggly", "stragglier", "straggliest" ],
	[ "giggly", "gigglier", "giggliest" ],
	[ "dangly", "danglier", "dangliest" ],
	[ "swirly", "swirlier", "swirliest" ],
	[ "jiggly", "jigglier", "jiggliest" ],
	[ "treacly", "treaclier", "treacliest" ],
	[ "dilly", "dillier", "dilliest" ],
	[ "snuggly", "snugglier", "snuggliest" ],
	[ "fiddly", "fiddlier", "fiddliest" ],
	[ "rattly", "rattlier", "rattliest" ],
];
