module.exports = [
	// Latin: um - a, on - a
	[ "addendum", "addenda" ],
	[ "curriculum", "curricula" ],
	[ "criterion", "criteria" ],
	[ "memorandum", "memoranda" ],
	[ "ovum", "ova" ],
	[ "phenomenon", "phenomena" ],
	[ "referendum", "referenda" ],

	// Latin: a - ae
	[ "abscissa", "abscissae", "abscissæ", "abscissas" ],
	[ "agenda", "agendae", "agendæ", "agendas" ],
	[ "agora", "agorae", "agoræ" ],
	[ "ala", "alae", "alæ" ],
	[ "alga", "algae" ],
	[ "alga", "algae", "algæ" ],
	[ "alumna", "alumnae", "alumnæ" ],
	[ "amenorrhoea", "amenorrhoeae", "amenorrhoeæ", "amenorrhoeas" ],
	[ "amnesia", "amnesiae", "amnesiæ", "amnesias" ],
	[ "amoeba", "amoebae", "amoebæ", "amoebas" ],
	[ "amphora", "amphorae", "amphoræ" ],
	[ "anaethesia", "anaesthesiae", "anæsthesia", "anæsthesiæ", "anaesthesias" ],
	[ "antenna", "antennae", "antennæ", "antennas" ],
	[ "aqua", "aquae", "aquæ" ],
	[ "area", "areae", "areæ", "areas" ],
	[ "areola", "areolae", "areolæ", "areolas" ],
	[ "aula", "aulae", "aulæ", "aulas" ],
	[ "aura", "aurae", "auræ", "auras" ],
	[ "capsula", "capsulae", "capsulæ", "capsulas" ],
	[ "catapulta", "catapultae", "catapultæ", "catapultas" ],
	[ "cathedra", "cathedrae", "cathedræ", "cathedras" ],
	[ "corona", "coronae", "coronæ", "coronas" ],
	[ "diarrhoea", "diarrhoeae", "diarrhœa", "diarrhœæ", "diarrhoeas" ],
	[ "encyclopaedia", "encyclopaediae", "encyclopædia", "encyclopædiæ", "encyclopedias" ],
	[ "fabella", "fabellae", "fabellæ" ],
	[ "fibula", "fibulae", "fibulæ" ],
	[ "fistula", "fistulae", "fistulæ" ],
	[ "formula", "formulae", "formulæ", "formulas" ],
	[ "fossa", "fossae", "fossæ" ],
	[ "foveola", "foveolae", "foveolæ" ],
	[ "furcula", "furculae", "furculæ" ],
	[ "galea", "galeae", "galeæ" ],
	[ "gingiva", "gingivae", "gingivæ" ],
	[ "gonorrhoea", "gonorrhoeae", "gonorrhœa", "gonorrhœæ", "gonorrhoeas" ],
	[ "hernia", "herniae", "herniæ", "hernias" ],
	[ "hetaera", "hetaerae", "hetæra", "hetæræ", "hetaeras" ],
	[ "hora", "horae", "horæ" ],
	[ "hyaena", "hyaenae", "hyæna", "hyænæ", "hyaenas" ],
	[ "hydromedusa", "hydromedusae", "hydromedusæ" ],
	[ "hyena", "hyenae", "hyenæ", "hyenas" ],
	[ "hyperbola", "hyperbolae", "hyperbolæ", "hyperbolas" ],
	[ "idea", "ideae", "ideæ", "ideas" ],
	[ "larva", "larvae", "larvæ" ],
	[ "longa", "longae", "longæ" ],
	[ "macula", "maculae", "maculæ" ],
	[ "maxilla", "maxillae", "maxillæ" ],
	[ "maxima", "maximae", "maximæ" ],
	[ "media", "mediae", "mediæ" ],
	[ "medulla", "medullae", "medullæ" ],
	[ "medusa", "medusae", "medusæ" ],
	[ "mensa", "mensae", "mensæ" ],
	[ "metra", "metrae", "metræ" ],
	[ "microfauna", "microfaunae", "microfaunæ" ],
	[ "microflora", "microflorae", "microfloræ" ],
	[ "mina", "minae", "minæ" ],
	[ "minutia", "minutiae", "minutiæ" ],
	[ "molecula", "moleculae", "moleculæ", "moleculas" ],
	[ "monomania", "monomaniae", "monomaniæ" ],
	[ "mora", "morae", "moræ" ],
	[ "natura", "naturae", "naturæ" ],
	[ "nebula", "nebulae", "nebulæ" ],
	[ "onomatopoeia", "onomatopoeiae", "onomatopoeiæ" ],
	[ "oötheca", "oöthecae", "oöthecæ" ],
	[ "palaestra", "palaestrae", "palaestræ" ],
	[ "panacea", "panaceae", "panaceæ", "panaceas" ],
	[ "papilla", "papillae", "papillæ" ],
	[ "papilloma", "papillomae", "papillomæ", "papillomas" ],
	[ "parabola", "parabolae", "parabolæ", "parabolas" ],
	[ "paraphilia", "paraphiliae", "paraphiliæ", "paraphilias" ],
	[ "persona", "personae", "personæ", "personas" ],
	[ "pharmacopoeia", "pharmacopoeiae", "pharmacopœia", "pharmacopœiæ" ],
	[ "pinna", "pinnae", "pinnæ" ],
	[ "planta", "plantae", "plantæ" ],
	[ "pleura", "pleurae", "pleuræ" ],
	[ "pupa", "pupae", "pupæ" ],
	[ "retina", "retinae", "retinæ", "retinas" ],
	[ "saliva", "salivae", "salivæ", "salivas" ],
	[ "scapula", "scapulae", "scapulæ" ],
	[ "scrofula", "scrofulae", "scrofulæ" ],
	[ "sequela", "sequelae", "sequelæ" ],
	[ "spatula", "spatulae", "spatulæ", "spatulas" ],
	[ "spermatheca", "spermathecae", "spermathecæ" ],
	[ "squama", "squamae", "squamæ" ],
	[ "stipula", "stipulae", "stipulæ" ],
	[ "stria", "striae", "striæ" ],
	[ "subpoena", "subpoenae", "subpœna", "subpœnæ", "subpoenas" ],
	[ "summa", "summae", "summæ", "summas" ],
	[ "synaesthesia", "synaesthesiae", "synæsthesia", "synæsthesiæ", "synaesthesias" ],
	[ "taenia", "taeniae", "taeniæ" ],
	[ "testa", "testae", "testæ" ],
	[ "tibia", "tibiae", "tibiæ" ],
	[ "toga", "togae", "togæ" ],
	[ "trachea", "tracheae", "tracheæ", "tracheas" ],
	[ "ulna", "ulnae", "ulnæ" ],
	[ "urethra", "urethrae", "urethræ", "urethras" ],
	[ "uva", "uvae", "uvæ" ],
	[ "uvula", "uvulae", "uvulæ" ],
	[ "vagina", "vaginae", "vaginæ", "vaginas" ],
	[ "vertebra", "vertebrae", "vertebræ", "vertebras" ],
	[ "vesica", "vesicae", "vesicæ" ],
	[ "via", "viae", "viæ" ],
	[ "vibratiuncula", "vibratiunculae", "vibratiunculæ" ],
	[ "vita", "vitae", "vitæ" ],
	[ "vulva", "vulvae", "vulvæ", "vulvas" ],
	[ "zona", "zonae", "zonæ" ],

	// Latin: consonant+is - consonant+es
	[ "avis", "aves" ],
	[ "epipubis", "epipubes" ],
	[ "hemipenis", "hemipenes" ],
	[ "jejunoileitis", "jejunoileites" ],
	[ "lymphadenitis", "lymphadenites", "lymphadenitides" ],
	[ "mantis", "mantes" ],
	[ "naris", "nares" ],
	[ "palatonaris", "palatonares" ],
	[ "pelvis", "pelves" ],
	[ "penis", "penes" ],
	[ "pileipellis", "pileipelles" ],
	[ "postnaris", "postnares" ],
	[ "prepubis", "prepubes" ],
	[ "pseudopenis", "pseudopenes" ],
	[ "pubis", "pubes" ],
	[ "sternochondroscapularis", "sternochondroscapulares" ],
	[ "tax", "taxi", "taxis", "taxes" ],
	[ "testis", "testes" ],

	// Latin: us - ora/era
	[ "corpus", "corpora" ],
	[ "genus", "genera" ],
	[ "opus", "opera" ],

	// Latin: is - idis (see also a regex rule for subcase itis - itides)
	[ "aegis", "aegides", "ægis", "ægides" ],
	[ "allantois", "allantoides" ],
	[ "aphis", "aphides" ],
	[ "apoapsis", "apoapsides" ],
	[ "apsis", "apside", "apsides" ],
	[ "basis", "bases", "base" ],
	[ "chlamys", "chlamydes" ],
	[ "chrysalis", "chrysalides" ],
	[ "coronis", "coronides" ],
	[ "ephelis", "ephelides" ],
	[ "ephemeris", "ephemerides" ],
	[ "epiglottis", "epiglottides" ],
	[ "hyporhachis", "hyporhachides" ],
	[ "ibis", "ibides" ],
	[ "incus", "incudes" ],
	[ "iris", "irides irises" ],
	[ "lagopus", "lagopodes" ],
	[ "octaeteris", "octaeterides", "octæteris", "octæterides" ],
	[ "octopus", "octopodes", "octopi" ],
	[ "palus", "paludes" ],
	[ "pes", "pedes" ],
	[ "periapsis", "periapsides" ],
	[ "pholas", "pholades" ],
	[ "platypus", "platypodes" ],
	[ "pleurodesis", "pleurodeses" ],
	[ "proboscis", "proboscides" ],
	[ "proglottis", "proglottides" ],
	[ "pseudomonas", "pseudomonades" ],
	[ "pyxis", "pyxides" ],
	[ "rachis", "rachides" ],
	[ "stapes", "stapedes" ],
	[ "tripus", "tripodes" ],

	// Latin inx/anx/ex - inges/anges/eges (see also regex rule yx/ynx/inx - yges/ynges/inges)
	[ "phalanx", "phalange", "phalangue", "phalanges" ],
	[ "remix", "remixes", "remiges" ],
	[ "sphex", "spheges" ],
	[ "syrinx", "syringe", "syringes" ],

	// Latin regularized
	[ "appendix", "appendices", "appendixes" ],
	[ "bacterium", "bacteria", "bacterias" ],
	[ "cactus", "cactuses", "cacti" ],
	[ "cicatrix", "cicatrice", "cicatrices" ],
	[ "complex", "complexes", "complices", "complice" ],
	[ "curriculum", "curricula", "curriculums" ],
	[ "ghetto", "ghettos", "ghettoes", "ghetti" ],
	[ "index", "indices", "indexes" ],
	[ "libretto", "librettos", "libretti" ],
	[ "millennium", "millennia", "millenniums" ],
	[ "postfix", "postfices", "postfixes" ],
	[ "prefix", "prefices", "prefixes" ],
	[ "referendum", "referenda", "referendums" ],
	[ "radius", "radii", "radiuses", "radio" ],
	[ "stadium", "stadia", "stadiums" ],
	[ "suffix", "suffices", "suffixes" ],
	[ "syllabus", "syllabuses", "syllabi" ],
	[ "terminus", "termini", "terminuses" ],
	[ "thesaurus", "thesauri", "thesauruses" ],
	[ "virus", "viri", "viruses" ],

	// Latin regularized a - ata
	[ "adenoma", "adenomas", "adenomata" ],
	[ "ænigma", "ænigmas", "ænigmata" ],
	[ "ameloblastoma", "ameloblastomas", "ameloblastomata" ],
	[ "anathema", "anathemas", "anathemata" ],
	[ "aroma", "aromas", "aromata" ],
	[ "asthma", "asthmas", "asthmata" ],
	[ "atheroma", "atheromas", "atheromata" ],
	[ "automa", "automas", "automata" ],
	[ "axioma", "axiomas", "axiomata" ],
	[ "chasma", "chasmas", "chasmata" ],
	[ "cœloma", "cœlomas", "cœlomata" ],
	[ "comma", "commas", "commata" ],
	[ "desidera", "desideras", "desiderata" ],
	[ "dilemma", "dilemmas", "dilemmata" ],
	[ "diploma", "diplomas", "diplomata" ],
	[ "dogma", "dogmas", "dogmata" ],
	[ "drama", "dramas", "dramata" ],
	[ "eczema", "eczemas", "eczemata" ],
	[ "endothelioma", "endotheliomas", "endotheliomata" ],
	[ "enigma", "enigmas", "enigmata" ],
	[ "erra", "erras", "errata" ],
	[ "fibroma", "fibromas", "fibromata" ],
	[ "glioma", "gliomas", "gliomata" ],
	[ "gonadoblastoma", "gonadoblastomas", "gonadoblastomata" ],
	[ "haematoma", "haematomas", "haematomata" ],
	[ "hæmatoma", "hæmatomas", "hæmatomata" ],
	[ "idioma", "idiomas", "idiomata" ],
	[ "lemma", "lemmas", "lemmata" ],
	[ "lymphœdema", "lymphœdemas", "lymphœdemata" ],
	[ "lymphoma", "lymphomas", "lymphomata" ],
	[ "melisma", "melismas", "melismata" ],
	[ "melodrama", "melodramas", "melodramata" ],
	[ "mesothelioma", "mesotheliomas", "mesotheliomata" ],
	[ "myeloma", "myelomas", "myelomata" ],
	[ "myoma", "myomas", "myomata" ],
	[ "œdema", "œdemas", "œdemata" ],
	[ "pancrea", "pancreas", "pancreata" ],
	[ "phantasma", "phantasmas", "phantasmata" ],
	[ "problema", "problemas", "problemata" ],
	[ "sarcoma", "sarcomas", "sarcomata" ],
	[ "schema", "schemas", "schemata" ],
	[ "stigma", "stigmas", "stigmata" ],
	[ "stoma", "stomas", "stomata" ],
	[ "stra", "stras", "strata" ],
	[ "substra", "substras", "substrata" ],
	[ "teratoma", "teratomas", "teratomata" ],
	[ "trauma", "traumas", "traumata" ],
	[ "xanthelasma", "xanthelasmas", "xanthelasmata" ],
	[ "zeugma", "zeugmas", "zeugmata" ],

	// French
	[ "beau", "beaux" ],
	[ "chateau", "chateaux" ],
	[ "tableau", "tableaux" ],

	// Ch exclusions
	[ "epoch", "epochs" ],
	[ "stomach", "stomachs" ],

	// Not changing
	[ "barracks", "barracks" ],
	[ "clothes", "clothes" ],
	[ "deer", "deer" ],
	[ "news", "news" ],
	[ "series", "series" ],

	// Miscellaneous
	[ "alias", "aliases" ],
	[ "bus", "buses" ],
	[ "child", "children" ],
	[ "circus", "circuses" ],
	[ "database", "databases" ],
	[ "echo", "echoes" ],
	[ "equinox", "equinoces" ],
	[ "ex", "exes" ],
	[ "foot", "feet" ],
	[ "goose", "geese" ],
	[ "keyphrase", "keyphrases" ],
	[ "louse", "lice" ],
	[ "man", "men" ],
	[ "mouse", "mice" ],
	[ "movie", "movies" ],
	[ "ox", "oxen" ],
	[ "person", "people" ],
	[ "phrase", "phrases" ],
	[ "quiz", "quizzes" ],
	[ "shoe", "shoes" ],
	[ "sex", "sexes" ],
	[ "status", "statuses" ],
	[ "tooth", "teeth" ],
];
