export const SET_PERFORMANCE_BATCH_SIZE = "SET_PERFORMANCE_BATCH_SIZE";
export const SET_PERFORMANCE_RESEARCHES = "SET_PERFORMANCE_RESEARCHES";
export const SET_PERFORMANCE_RESULTS = "SET_PERFORMANCE_RESULTS";
export const ADD_PERFORMANCE_RESULT = "ADD_PERFORMANCE_RESULT";
