name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "featurerequest"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue, please search for duplicate issues to prevent opening a duplicate feature request. If there is already an open existing request, please leave a comment there.

  - type: textarea
    id: problem-relation
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: feature-justification
    attributes:
      label: Why do you think this feature is something we should consider for the Yoast SEO plugins?
      description: Explain why this feature would be valuable for Yoast SEO users.
      placeholder: Explain the benefits and value this feature would bring...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, mockups, or examples about the feature request here.
      placeholder: Add any additional context, screenshots, or examples...
