// These auxiliaries are filtered from the beginning and end of word combinations in the prominent words.
var filteredAuxiliaries =  [
	"werde",
	"wirst",
	"wird",
	"werdet",
	"wurde",
	"ward",
	"wurdest",
	"wardst",
	"wurden",
	"wurdet",
	"worden",
	"werdest",
	"würde",
	"würdest",
	"würden",
	"würdet",
	"bekomme",
	"bekommst",
	"bekommt",
	"bekam",
	"bekamst",
	"bekamen",
	"bekommest",
	"bekommet",
	"bekäme",
	"bekämest",
	"bekämst",
	"bekämen",
	"bekämet",
	"bekämt",
	"kriege",
	"kriegst",
	"kriegt",
	"kriegte",
	"kriegtest",
	"kriegten",
	"kriegtet",
	"gekriegt",
	"kriegest",
	"krieget",
	"gehöre",
	"gehörst",
	"gehört",
	"gehörte",
	"gehörtest",
	"gehörten",
	"gehörtet",
	"gehörest",
	"gehöret",
	"erhalte",
	"erhältst",
	"erhält",
	"erhaltet",
	"erhielt",
	"erhieltest",
	"erhieltst",
	"erhielten",
	"erhieltet",
	"erhaltest",
	"erhielte",
];

// These auxiliaries are not filtered from the beginning of word combinations in the prominent words.
var notFilteredAuxiliaries = [
	"werden",
	"bekommen",
	"kriegen",
	"gehören",
	"erhalten",
];

module.exports = function() {
	return {
		filteredAuxiliaries: filteredAuxiliaries,
		notFilteredAuxiliaries: notFilteredAuxiliaries,
		all: filteredAuxiliaries.concat( notFilteredAuxiliaries ),
	};
};

