### Creates a new request
GET http://localhost:3000/analyze
Content-Type: application/json

{
    "text": "<p>Yoast SEO is a search engine optimization (SEO) tool plug-in for WordPress.</p><p>Yoast SEO created its first WordPress SEO plugin in 2007 - originally named WordPress SEO: it was developed as a WordPress plugin by SEO consultant Joost de Valk. In 2012, the plug-in was renamed Yoast SEO. In 2015, Yoast hosted the inaugural YoastCon conference at the Lindenberg Nijmegen Culture House in Nijmegen, Netherlands. In 2015, a flaw was discovered in version 1.7.3.3 and earlier versions. The flaw could have left users of Yoast SEO open to hackers and was discovered by a security consultant.</p>",
    "keyword": "Yoast SEO"
}

### Run a request in a different language
GET http://localhost:3000/analyze
Content-Type: application/json

{
    "text": "<p>Zoekmachineoptimalisatie (Engels: <em>search engine optimization (SEO)</em>) is een onderdeel van zoekmachinemarketing en kan worden gedefinieerd als het geheel aan activiteiten bedoeld om een webpagina hoog te laten scoren in de organische zoekresultaten van een zoekmachine, op de voor die webpagina relevante trefwoorden. Aangezien een vermelding in die organische resultaten gratis is, vormen deze zoekresultaten een interessant alternatief voor zoekmachineadverteren. SEO kan een bedrijf concurrentievoordeel opleveren.</p>",
    "keyword": "SEO",
    "locale": "nl"
}
