name: Manual Run Commands

# Allow the workflow to be triggered manually
on:
  workflow_dispatch:
    inputs:
      command:
        description: "Command to run"
        required: false
        default: "echo Hello, World!"

jobs:
  run-commands:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v3

      # Run the specified command or default to echoing a message
      - name: Run specified command
        run: ${{ github.event.inputs.command }}
