/** @module config/syllables */

var getLanguage = require( "../helpers/getLanguage.js" );
var isUndefined = require( "lodash/isUndefined" );

/**
 * Returns an array with syllables.
 * Subtractsyllables are counted as two and need to be counted as one.
 * Addsyllables are counted as one but need to be counted as two.
 * Exclusionwords are removed from the text to be counted seperatly.
 *
 * @returns {object}
 */
var syllableLanguageConfig = {
	de: {
		"vowels": "aeiouyäöüáéâàèîêâûôœ",
		"deviations": {
			"vowels": [
				{
					"fragments": ["ouil", "deaux", "deau$", "oard", "äthiop", "euil", "veau", "eau$", "ueue", "lienisch", "ance$", "ence$", "time$",
						"once$", "ziat", "guette", "ête$", "ôte$", "[hmp]omme$", "[qdscn]ue$", "chaise", "aire$", "ture$", "êpe$", "[^q]ui$", "tiche$",
						"ource$", "vice$", "oile$", "zial", "cruis", "leas", "blue", "lead", "coa[ct]", "^deal", "[^i]deal", "[fw]eat", "cache[^t]", "[lsx]sed$"],
					"countModifier": -1
				},
				{
					"fragments": ["aau", "a[äöüo]", "äue", "äeu", "aei", "aue", "aeu", "ael", "ayo", "ai[aeo]", "saik", "aismus", "ä[aeoi]", "auä", "éa",
						"e[äaoö]", "ei[eo]", "ee[eiuoa]", "eu[aäe]", "eum$", "eü", "o[aäöü]", "poet", "oo[eo]", "oie", "oei[^l]", "oeu[^f]", "öa", "[fgrz]ieu",
						"mieun", "tieur", "ieum", "i[aiuü]", "[^l]iä", "[^s]chien", "io[wqtpdfhjkxcvbmu]", "[brpdhvm]ion", "[lr]ior", "[^g]ios",
						"[^g]iog", "[rd]ioz", "elioz", "zioni", "bio[lnzr]", "iö[^s]", "ie[ei]", "rier$", "öi[ge]", "[^r]oïsch",
						"[^qgv]u[aeéioöuü]", "quie$", "quie[^s]", "uäu", "^us-", "^it-", "üe", "naiv", "aisch$", "aische$", "[lst]ien", "dien$", "gois", "[^g]rient",
						"[aeiou]y[aeiou]", "byi", "yä", "[a-z]yo", "[a-z]ya", "yau", "yie", "koor", "scient", "eriel", "[bdg]oing"],
					"countModifier": 1
				},
				// These are the second-pass addSyllables:
				{
					"fragments": ["ioi", "ioo", "ioa", "eio", "iii", "oai", "eueu"],
					"countModifier": 1
				}
			],
			"words": {
				"full": [
					{"word": "beach", "syllables": 1},
					{"word": "beat", "syllables": 1},
					{"word": "beau", "syllables": 1},
					{"word": "beaune", "syllables": 1},
					{"word": "belle", "syllables": 1},
					{"word": "bouche", "syllables": 1},
					{"word": "brake", "syllables": 1},
					{"word": "cache", "syllables": 1},
					{"word": "cache", "syllables": 1},
					{"word": "chaiselongue", "syllables": 2},
					{"word": "choke", "syllables": 1},
					{"word": "cordiale", "syllables": 3},
					{"word": "core", "syllables": 1},
					{"word": "dope", "syllables": 1},
					{"word": "eat", "syllables": 1},
					{"word": "eye", "syllables": 1},
					{"word": "fake", "syllables": 1},
					{"word": "fame", "syllables": 1},
					{"word": "fatigue", "syllables": 2},
					{"word": "femme", "syllables": 1},
					{"word": "force", "syllables": 1},
					{"word": "game", "syllables": 1},
					{"word": "games", "syllables": 1},
					{"word": "gate", "syllables": 1},
					{"word": "grande", "syllables": 1},
					{"word": "ice", "syllables": 1},
					{"word": "ion", "syllables": 2},
					{"word": "joke", "syllables": 1},
					{"word": "jupe", "syllables": 1},
					{"word": "maisch", "syllables": 1},
					{"word": "maische", "syllables": 2},
					{"word": "move", "syllables": 1},
					{"word": "native", "syllables": 2},
					{"word": "nice", "syllables": 1},
					{"word": "one", "syllables": 1},
					{"word": "pipe", "syllables": 1},
					{"word": "prime", "syllables": 1},
					{"word": "rate", "syllables": 1},
					{"word": "rhythm", "syllables": 2}
					{"word": "ride", "syllables": 1},
					{"word": "rides", "syllables": 1},
					{"word": "rien", "syllables": 2},
					{"word": "save", "syllables": 1},
					{"word": "science", "syllables": 2},
					{"word": "siècle", "syllables": 1},
					{"word": "site", "syllables": 1},
					{"word": "suite", "syllables": 1},
					{"word": "take", "syllables": 1},
					{"word": "taupe", "syllables": 1},
					{"word": "universe", "syllables": 3},
					{"word": "vogue", "syllables": 1},
					{"word": "wave", "syllables": 1},
					{"word": "zion", "syllables": 2},
				],
				"fragments": {
					"global": [
						{"word": "abreaktion", "syllables": 4},
						{"word": "adware", "syllables": 2},
						{"word": "affaire", "syllables": 3},
						{"word": "aiguière", "syllables": 2},
						{"word": "anisette", "syllables": 3},
						{"word": "appeal", "syllables": 2},
						{"word": "backstage", "syllables": 2},
						{"word": "bankrate", "syllables": 2},
						{"word": "baseball", "syllables": 2},
						{"word": "basejump", "syllables": 2},
						{"word": "beachcomber", "syllables": 3},
						{"word": "beachvolleyball", "syllables": 4},
						{"word": "beagle", "syllables": 2},
						{"word": "beamer", "syllables": 2},
						{"word": "beamer", "syllables": 2},
						{"word": "béarnaise", "syllables": 3},
						{"word": "beaufort", "syllables": 2},
						{"word": "beaujolais", "syllables": 3},
						{"word": "beauté", "syllables": 2},
						{"word": "beauty", "syllables": 2},
						{"word": "belgier", "syllables": 3},
						{"word": "bestien", "syllables": 2},
						{"word": "biskuit", "syllables": 2},
						{"word": "bleach", "syllables": 1},
						{"word": "board", "syllables": 1},
						{"word": "boat", "syllables": 1},
						{"word": "bodysuit", "syllables": 3},
						{"word": "bordelaise", "syllables": 3},
						{"word": "break", "syllables": 1},
						{"word": "build", "syllables": 1},
						{"word": "bureau", "syllables": 2},
						{"word": "business", "syllables": 2},
						{"word": "cabrio", "syllables": 3},
						{"word": "cabriolet", "syllables": 4},
						{"word": "cachesexe", "syllables": 2},
						{"word": "camaieu", "syllables": 3},
						{"word": "canyon", "syllables": 2},
						{"word": "case", "syllables": 1},
						{"word": "catsuit", "syllables": 2},
						{"word": "centime", "syllables": 3},
						{"word": "champion", "syllables": 2},
						{"word": "championat", "syllables": 3},
						{"word": "chapiteau", "syllables": 3},
						{"word": "chateau", "syllables": 2},
						{"word": "château", "syllables": 2},
						{"word": "cheat", "syllables": 1},
						{"word": "cheese", "syllables": 1},
						{"word": "chihuahua", "syllables": 3},
						{"word": "choice", "syllables": 1},
						{"word": "circonflexe", "syllables": 3},
						{"word": "clean", "syllables": 1},
						{"word": "cloche", "syllables": 1},
						{"word": "close", "syllables": 1},
						{"word": "clothes", "syllables": 1},
						{"word": "commerce", "syllables": 2},
						{"word": "crime", "syllables": 1},
						{"word": "crossrate", "syllables": 2},
						{"word": "cuisine", "syllables": 2},
						{"word": "culotte", "syllables": 2},
						{"word": "death", "syllables": 1},
						{"word": "defense", "syllables": 2},
						{"word": "détente", "syllables": 2},
						{"word": "dread", "syllables": 1},
						{"word": "dream", "syllables": 1},
						{"word": "dresscode", "syllables": 2},
						{"word": "dungeon", "syllables": 2},
						{"word": "easy", "syllables": 2},
						{"word": "engagement", "syllables": 3},
						{"word": "entente", "syllables": 2},
						{"word": "eye-catcher", "syllables": 3},
						{"word": "eyecatcher", "syllables": 3},
						{"word": "eyeliner", "syllables": 3},
						{"word": "eyeword", "syllables": 2},
						{"word": "fashion", "syllables": 2},
						{"word": "ferien", "syllables": 3},
						{"word": "fineliner", "syllables": 3},
						{"word": "fisheye", "syllables": 2},
						{"word": "flake", "syllables": 1},
						{"word": "flambeau", "syllables": 2},
						{"word": "flatrate", "syllables": 2},
						{"word": "fleece", "syllables": 1},
						{"word": "fraîche", "syllables": 1},
						{"word": "freak", "syllables": 1},
						{"word": "frites", "syllables": 1},
						{"word": "future", "syllables": 2},
						{"word": "gaelic", "syllables": 2},
						{"word": "game-show", "syllables": 2},
						{"word": "gameboy", "syllables": 2},
						{"word": "gamepad", "syllables": 2},
						{"word": "gameplay", "syllables": 2},
						{"word": "gameport", "syllables": 2},
						{"word": "gameshow", "syllables": 2},
						{"word": "garigue", "syllables": 2},
						{"word": "garrigue", "syllables": 2},
						{"word": "gatefold", "syllables": 2},
						{"word": "gateway", "syllables": 2},
						{"word": "geflashed", "syllables": 2},
						{"word": "georgier", "syllables": 4},
						{"word": "goal", "syllables": 1},
						{"word": "grapefruit", "syllables": 2},
						{"word": "great", "syllables": 1},
						{"word": "groupware", "syllables": 2},
						{"word": "gueule", "syllables": 1},
						{"word": "guide", "syllables": 1},
						{"word": "guilloche", "syllables": 2},
						{"word": "gynäzeen", "syllables": 4},
						{"word": "gynözeen", "syllables": 4},
						{"word": "haircare", "syllables": 2},
						{"word": "hardcore", "syllables": 2},
						{"word": "hardware", "syllables": 2},
						{"word": "head", "syllables": 1},
						{"word": "hearing", "syllables": 2},
						{"word": "heart", "syllables": 1},
						{"word": "heavy", "syllables": 2},
						{"word": "hedge", "syllables": 1},
						{"word": "heroin", "syllables": 3},
						{"word": "inclusive", "syllables": 3},
						{"word": "initiative", "syllables": 4},
						{"word": "inside", "syllables": 2},
						{"word": "jaguar", "syllables": 3},
						{"word": "jalousette", "syllables": 3},
						{"word": "jeans", "syllables": 1},
						{"word": "jeunesse", "syllables": 2},
						{"word": "juice", "syllables": 1},
						{"word": "jukebox", "syllables": 2},
						{"word": "jumpsuit", "syllables": 2},
						{"word": "kanarien", "syllables": 4},
						{"word": "kapriole", "syllables": 4},
						{"word": "karosserielinie", "syllables": 6},
						{"word": "konopeen", "syllables": 4},
						{"word": "lacrosse", "syllables": 2},
						{"word": "laplace", "syllables": 2},
						{"word": "late-", "syllables": 1},
						{"word": "league", "syllables": 1},
						{"word": "learn", "syllables": 1},
						{"word": "légière", "syllables": 2},
						{"word": "lizenziat", "syllables": 4},
						{"word": "load", "syllables": 1},
						{"word": "lotterielos", "syllables": 4},
						{"word": "lounge", "syllables": 1},
						{"word": "lyzeen", "syllables": 3},
						{"word": "madame", "syllables": 2},
						{"word": "mademoiselle", "syllables": 3},
						{"word": "magier", "syllables": 3},
						{"word": "make-up", "syllables": 2},
						{"word": "malware", "syllables": 2},
						{"word": "management", "syllables": 3},
						{"word": "manteau", "syllables": 2},
						{"word": "mausoleen", "syllables": 4},
						{"word": "mauve", "syllables": 1},
						{"word": "medien", "syllables": 3},
						{"word": "mesdames", "syllables": 2},
						{"word": "mesopotamien", "syllables": 6},
						{"word": "milliarde", "syllables": 3},
						{"word": "missile", "syllables": 2},
						{"word": "miszellaneen", "syllables": 5},
						{"word": "mousse", "syllables": 1},
						{"word": "mousseline", "syllables": 3},
						{"word": "museen", "syllables": 3},
						{"word": "musette", "syllables": 2},
						{"word": "nahuatl", "syllables": 2},
						{"word": "noisette", "syllables": 2},
						{"word": "notebook", "syllables": 2},
						{"word": "nuance", "syllables": 3},
						{"word": "nuklease", "syllables": 4},
						{"word": "odeen", "syllables": 3},
						{"word": "offline", "syllables": 2},
						{"word": "offside", "syllables": 2},
						{"word": "oleaster", "syllables": 4},
						{"word": "on-stage", "syllables": 2},
						{"word": "online", "syllables": 2},
						{"word": "orpheen", "syllables": 3},
						{"word": "parforceritt", "syllables": 3},
						{"word": "patiens", "syllables": 2},
						{"word": "patient", "syllables": 2},
						{"word": "peace", "syllables": 1},
						{"word": "peace", "syllables": 1},
						{"word": "peanuts", "syllables": 2},
						{"word": "people", "syllables": 2},
						{"word": "perineen", "syllables": 4},
						{"word": "peritoneen", "syllables": 5},
						{"word": "picture", "syllables": 2},
						{"word": "piece", "syllables": 1},
						{"word": "pipeline", "syllables": 2},
						{"word": "plateau", "syllables": 2},
						{"word": "poesie", "syllables": 3},
						{"word": "poleposition", "syllables": 4},
						{"word": "portemanteau", "syllables": 3},
						{"word": "portemonnaie", "syllables": 3},
						{"word": "primerate", "syllables": 2},
						{"word": "primerate", "syllables": 2},
						{"word": "primetime", "syllables": 2},
						{"word": "protease", "syllables": 4},
						{"word": "protein", "syllables": 3},
						{"word": "prytaneen", "syllables": 4},
						{"word": "quotient", "syllables": 2},
						{"word": "radio", "syllables": 3},
						{"word": "reader", "syllables": 2},
						{"word": "ready", "syllables": 2},
						{"word": "reallife", "syllables": 2},
						{"word": "repeat", "syllables": 2},
						{"word": "retake", "syllables": 2},
						{"word": "rigole", "syllables": 2},
						{"word": "risolle", "syllables": 2},
						{"word": "road", "syllables": 1},
						{"word": "roaming", "syllables": 2},
						{"word": "roquefort", "syllables": 2},
						{"word": "safe", "syllables": 1},
						{"word": "savonette", "syllables": 3},
						{"word": "sciencefiction", "syllables": 3},
						{"word": "search", "syllables": 1},
						{"word": "selfmade", "syllables": 2},
						{"word": "septime", "syllables": 3},
						{"word": "serapeen", "syllables": 4},
						{"word": "service", "syllables": 2},
						{"word": "serviette", "syllables": 2},
						{"word": "share", "syllables": 1},
						{"word": "shave", "syllables": 1},
						{"word": "shore", "syllables": 1},
						{"word": "sidebar", "syllables": 2},
						{"word": "sideboard", "syllables": 2},
						{"word": "sidekick", "syllables": 2},
						{"word": "silhouette", "syllables": 3},
						{"word": "sitemap", "syllables": 2},
						{"word": "slide", "syllables": 1},
						{"word": "sneak", "syllables": 1},
						{"word": "soap", "syllables": 1},
						{"word": "softcore", "syllables": 2},
						{"word": "software", "syllables": 2},
						{"word": "soutanelle", "syllables": 3},
						{"word": "speak", "syllables": 1},
						{"word": "special", "syllables": 2},
						{"word": "spracheinstellung", "syllables": 5},
						{"word": "spyware", "syllables": 2},
						{"word": "square", "syllables": 1},
						{"word": "stagediving", "syllables": 3},
						{"word": "stakeholder", "syllables": 3},
						{"word": "statement", "syllables": 2},
						{"word": "steady", "syllables": 2},
						{"word": "steak", "syllables": 1},
						{"word": "stealth", "syllables": 1},
						{"word": "steam", "syllables": 1},
						{"word": "stoned", "syllables": 1},
						{"word": "stracciatella", "syllables": 4},
						{"word": "stream", "syllables": 1},
						{"word": "stride", "syllables": 1},
						{"word": "strike", "syllables": 1},
						{"word": "suitcase", "syllables": 2},
						{"word": "sweepstake", "syllables": 2},
						{"word": "t-bone", "syllables": 2},
						{"word": "t-shirt", "syllables": 1},
						{"word": "tailgate", "syllables": 2},
						{"word": "take-off", "syllables": 2},
						{"word": "take-over", "syllables": 3},
						{"word": "takeaway", "syllables": 3},
						{"word": "takeoff", "syllables": 2},
						{"word": "takeover", "syllables": 3},
						{"word": "throat", "syllables": 1},
						{"word": "time-out", "syllables": 2},
						{"word": "timelag", "syllables": 2},
						{"word": "timeline", "syllables": 2},
						{"word": "timesharing", "syllables": 3},
						{"word": "toast", "syllables": 1},
						{"word": "traubenmaische", "syllables": 4},
						{"word": "tristesse", "syllables": 2},
						{"word": "usenet", "syllables": 2},
						{"word": "varietät", "syllables": 4},
						{"word": "varieté", "syllables": 4},
						{"word": "vinaigrette", "syllables": 3},
						{"word": "vintage", "syllables": 2},
						{"word": "violett", "syllables": 3},
						{"word": "voice", "syllables": 1},
						{"word": "wakeboard", "syllables": 2},
						{"word": "washed", "syllables": 1},
						{"word": "waveboard", "syllables": 2},
						{"word": "wear", "syllables": 1},
						{"word": "wear", "syllables": 1},
						{"word": "website", "syllables": 2},
						{"word": "white", "syllables": 1},
						{"word": "widescreen", "syllables": 2},
						{"word": "wire", "syllables": 1},
						{"word": "yacht", "syllables": 1},
						{"word": "yorkshire", "syllables": 2},
						{"word": "éprouvette", "syllables": 3, "notFollowedBy": ["n"]},
						{"word": "galette", "syllables": 2, "notFollowedBy": ["n"]},
						{"word": "gigue", "syllables": 1, "notFollowedBy": ["n"]},
						{"word": "groove", "syllables": 1, "notFollowedBy": ["n"]},
						{"word": "morgue", "syllables": 1, "notFollowedBy": ["n"]},
						{"word": "paillette", "syllables": 2, "notFollowedBy": ["n"]},
						{"word": "raclette", "syllables": 2, "notFollowedBy": ["n"]},
						{"word": "roulette", "syllables": 2, "notFollowedBy": ["n"]},
						{"word": "spike", "syllables": 1, "notFollowedBy": ["n"]},
						{"word": "style", "syllables": 1, "notFollowedBy": ["n"]},
						{"word": "tablette", "syllables": 2, "notFollowedBy": ["n"]},
						{"word": "grunge", "syllables": 1, "notFollowedBy": ["r"]},
						{"word": "size", "syllables": 1, "notFollowedBy": ["r"]},
						{"word": "value", "syllables": 1, "notFollowedBy": ["r"]},
						{"word": "quiche", "syllables": 1, "notFollowedBy": ["s"]},
						{"word": "house", "syllables": 1, "notFollowedBy": ["n", "s"]},
						{"word": "sauce", "syllables": 1, "notFollowedBy": ["n", "s"]},
						{"word": "space", "syllables": 1, "notFollowedBy": ["n", "s"]},
						{"word": "airline", "syllables": 2, "notFollowedBy": ["n", "r"]},
						{"word": "autosave", "syllables": 3, "notFollowedBy": ["n", "r"]},
						{"word": "bagpipe", "syllables": 2, "notFollowedBy": ["n", "r"]},
						{"word": "bike", "syllables": 1, "notFollowedBy": ["n", "r"]},
						{"word": "dance", "syllables": 1, "notFollowedBy": ["n", "r"]},
						{"word": "deadline", "syllables": 2, "notFollowedBy": ["n", "r"]},
						{"word": "halfpipe", "syllables": 2, "notFollowedBy": ["n", "r"]},
						{"word": "headline", "syllables": 2, "notFollowedBy": ["n", "r"]},
						{"word": "home", "syllables": 1, "notFollowedBy": ["n", "r"]},
						{"word": "hornpipe", "syllables": 2, "notFollowedBy": ["n", "r"]},
						{"word": "hotline", "syllables": 2, "notFollowedBy": ["n", "r"]},
						{"word": "infoline", "syllables": 3, "notFollowedBy": ["n", "r"]},
						{"word": "inline", "syllables": 2, "notFollowedBy": ["n", "r"]},
						{"word": "kite", "syllables": 1, "notFollowedBy": ["n", "r"]},
						{"word": "rollerblade", "syllables": 1, "notFollowedBy": ["n", "r"]},
						{"word": "score", "syllables": 1, "notFollowedBy": ["n", "r"]},
						{"word": "skyline", "syllables": 2, "notFollowedBy": ["n", "r"]},
						{"word": "slackline", "syllables": 2, "notFollowedBy": ["n", "r"]},
						{"word": "slice", "syllables": 1, "notFollowedBy": ["n", "r"]},
						{"word": "snooze", "syllables": 1, "notFollowedBy": ["n", "r"]},
						{"word": "storyline", "syllables": 3, "notFollowedBy": ["n", "r"]},
						{"word": "office", "syllables": 2, "notFollowedBy": ["s", "r"]},
						{"word": "space", "syllables": 1, "notFollowedBy": ["n", "s", "r"]},
						{"word": "tease", "syllables": 1, "notFollowedBy": ["n", "s", "r"]}
					],
					"atBeginningOrEnd": [
						{"word": "case", "syllables": 1},
						{"word": "life", "syllables": 1},
						{"word": "teak", "syllables": 1},
						{"word": "team", "syllables": 1},
						{"word": "creme", "syllables": 1, "notFollowedBy": ["n", "r"]},
						{"word": "crème", "syllables": 1, "notFollowedBy": ["n", "r"]},
						{"word": "drive", "syllables": 1, "notFollowedBy": ["n", "r"]},
						{"word": "skate", "syllables": 1, "notFollowedBy": ["n", "r"]},
						{"word": "update", "syllables": 2, "notFollowedBy": ["n", "r"]},
						{"word": "upgrade", "syllables": 2, "notFollowedBy": ["n", "r"]}
					],
					"atBeginning": [
						{"word": "anion", "syllables": 3},
						{"word": "facelift", "syllables": 2},
						{"word": "jiu", "syllables": 1},
						{"word": "pace", "syllables": 1},
						{"word": "shake", "syllables": 1},
						{"word": "tea", "syllables": 1},
						{"word": "trade", "syllables": 1}
					],
					"atEnd": [
						{"word": "face", "syllables": 1},
						{"word": "file", "syllables": 1},
						{"word": "mousse", "syllables": 1},
						{"word": "plate", "syllables": 1},
						{"word": "tape", "syllables": 1},
						{"word": "byte", "syllables": 1, "alsoFollowedBy": ["s"]},
						{"word": "cape", "syllables": 1, "alsoFollowedBy": ["s"]},
						{"word": "five", "syllables": 1, "alsoFollowedBy": ["s"]},
						{"word": "hype", "syllables": 1, "alsoFollowedBy": ["s"]},
						{"word": "leak", "syllables": 1, "alsoFollowedBy": ["s"]},
						{"word": "like", "syllables": 1, "alsoFollowedBy": ["s"]},
						{"word": "make", "syllables": 1, "alsoFollowedBy": ["s"]},
						{"word": "phone", "syllables": 1, "alsoFollowedBy": ["s"]},
						{"word": "rave", "syllables": 1, "alsoFollowedBy": ["s"]},
						{"word": "regime", "syllables": 2, "alsoFollowedBy": ["s"]},
						{"word": "statue", "syllables": 2, "alsoFollowedBy": ["s"]},
						{"word": "store", "syllables": 1, "alsoFollowedBy": ["s"]},
						{"word": "wave", "syllables": 1, "alsoFollowedBy": ["s"]},
						{"word": "date", "syllables": 1, "notFollowedBy": ["n"]},
						{"word": "image", "syllables": 2, "notFollowedBy": ["s"]}
					]
				}
			}
		}
	},
	en: {
		syllableExclusion: {
			subtractSyllables: {
				syllables: [ "cial", "tia", "cius", "cious", "giu", "ion", "iou", "sia$", "[^aeiuoyt]{2,}ed$", "[aeiouy][^aeiuoyts]{1,}e$", ".ely$", "[cg]h?e[sd]", "rved$", "rved", "[aeiouy][dt]es?$", "[aeiouy][^aeiouydt]e[sd]?$", "^[dr]e[aeiou][^aeiou]+$", "[aeiouy]rse$" ],
				multiplier: -1
			},
			addSyllables: {
				syllables: [ "ia", "riet", "dien", "iu", "io", "ii", "[aeiouym][bdp]le$", "[aeiou]{3}", "^mc", "ism$", "([^aeiouy])\1l$", "[^l]lien", "^coa[dglx].", "[^gq]ua[^auieo]", "dnt$", "uity$", "ie(r|st)", "[aeiouy]ing", "[aeiouw]y[aeiou]", "[^ao]ire[ds]", "[^ao]ire$"],
				multiplier: +1
			}

		},
		exclusionWords: [
			{ word: "business", syllables: 2 },
			{ word: "coheiress", syllables: 3 },
			{ word: "colonel", syllables: 2 },
			{ word: "heiress", syllables: 2 },
			// The abbreviation i.e. should be counted as 2 syllables.
			{ word: "i.e", syllables: 2},
			{ word: "shoreline", syllables: 2 },
			{ word: "simile", syllables: 3 },
			{ word: "unheired", syllables: 2 },
			{ word: "wednesday", syllables: 2 }
		],
		vowels: 'aeiouy'
	},
	nl: {
		syllableExclusion: {
			subtractSyllables: {
				syllables: [ "ue+$", "ue$", "dge+$", "dge$","[tcp]iënt" ,"ace$", "ace+$", "[br]each", "[ainpr]tiaal", "[io]tiaan", "gua[yc]", "[^i]deal", "^deal", "tive$", "base[^enr]", "base$", "load", "close[^rt]", "close$", "[^e]coke", "^coke", "drive[^r]", "drive$", "[^s]core$", "^core$", "face[^nt]", "face$", "cache[^clntx]", "cache$", "game[^nlr]", "game$" ],
				multiplier: -1
			},
			addSyllables: {
				syllables: [ "aä", "aeu", "aie", "ao", "ë", "eo", "eú", "ieau", "ea$", "ea+$", "ea[^u]", "ei[ej]", "eu[iu]", "ï", "iei", "ienne", "[^l]ieu[^w]", "[^l]ieu$", "[^l]ieu+$",  "i[auiy]", "stion", "[^cstx]io", "^sion","riè", "oö", "oa", "oeing", "oeyo", "oie", "[eu]ü", "[^q]u[oaeè]", "uie", "[aeolu]y[eéèaoóu]", "[bhnpr]ieel", "[bhnpr]iël" ],
				multiplier: +1
			}
		},
		// Exclusion words that are loan-words from English.
		exclusionWords: [
			{ word: "bye", syllables: 1 },
			{ word: "cure", syllables: 1 },
			{ word: "dei", syllables: 2 },
			{ word: "dope", syllables: 1 },
			{ word: "dude", syllables: 1 },
			{ word: "fake", syllables: 1 },
			{ word: "fame", syllables: 1 },
			{ word: "five", syllables: 1 },
			{ word: "hole", syllables: 1 },
			{ word: "least", syllables: 1 },
			{ word: "lone", syllables: 1 },
			{ word: "minute", syllables: 2 },
			{ word: "move", syllables: 1 },
			{ word: "nice", syllables: 1 },
			{ word: "one", syllables: 1 },
			{ word: "state", syllables: 1 },
			{ word: "surplace", syllables: 2 },
			{ word: "take", syllables: 1 },
			{ word: "trade", syllables: 1 },
			{ word: "wide", syllables: 1 }
		],
		partialExclusionWords: {
			// Exclusions that should be found anywhere in a string. Mostly loan-words from English and French.
			wordParts: {
				exclusionParts: [
					{ word: "adieu", syllables: 2 },
					{ word: "airline", syllables: 2 },
					{ word: "airmiles", syllables: 2 },
					{ word: "alien", syllables: 3 },
					{ word: "ambient", syllables: 3 },
					{ word: "announcement", syllables: 3 },
					{ word: "appearance", syllables: 3 },
					{ word: "appeasement", syllables: 3 },
					{ word: "atheneum", syllables: 4 },
					{ word: "awesome", syllables: 2 },
					{ word: "baccalaurei", syllables: 5 },
					{ word: "baccalaureus", syllables: 5 },
					{ word: "baseball", syllables: 3 },
					{ word: "basejump", syllables: 2 },
					{ word: "banlieue", syllables: 3 },
					{ word: "bapao", syllables: 2 },
					{ word: "barbecue", syllables: 3},
					{ word: "beamer", syllables: 2 },
					{ word: "beanie", syllables: 2 },
					{ word: "beat", syllables: 1 },
					{ word: "belle", syllables: 2 },
					{ word: "bête", syllables: 1 },
					{ word: "bingewatch", syllables: 2 },
					{ word: "blocnote", syllables: 2 },
					{ word: "blue", syllables: 1 },
					{ word: "board", syllables: 1 },
					{ word: "break", syllables: 1 },
					{ word: "broad", syllables: 1 },
					{ word: "bulls-eye", syllables: 2 },
					{ word: "business", syllables: 2 },
					{ word: "byebye", syllables: 2 },
					{ word: "cacao", syllables: 2 },
					{ word: "caesar", syllables: 2 },
					{ word: "camaieu", syllables: 3 },
					{ word: "caoutchouc", syllables: 2 },
					{ word: "carbolineum", syllables: 5 },
					{ word: "catchphrase", syllables: 1 },
					{ word: "carrier", syllables: 3 },
					{ word: "cheat", syllables: 1 },
					{ word: "cheese", syllables: 1 },
					{ word: "circonflexe", syllables: 3 },
					{ word: "clean", syllables: 1 },
					{ word: "cloak", syllables: 1 },
					{ word: "cobuying", syllables: 3 },
					{ word: "comeback", syllables: 2 },
					{ word: "comfortzone", syllables: 3 },
					{ word: "communiqué", syllables: 4 },
					{ word: "conopeum", syllables: 4 },
					{ word: "console", syllables: 2 },
					{ word: "corporate", syllables: 3 },
					{ word: "coûte", syllables: 1 },
					{ word: "creamer", syllables: 2 },
					{ word: "crime", syllables: 1 },
					{ word: "cruesli", syllables: 2 },
					{ word: "deadline", syllables: 2 },
					{ word: "deautoriseren", syllables: 6 },
					{ word: "deuce", syllables: 1 },
					{ word: "deum", syllables: 2 },
					{ word: "dirndl", syllables: 2 },
					{ word: "dread", syllables: 2 },
					{ word: "dreamteam", syllables: 2 },
					{ word: "drone", syllables: 1 },
					{ word: "enquête", syllables: 3 },
					{ word: "escape", syllables: 2 },
					{ word: "exposure", syllables: 3 },
					{ word: "extranei", syllables: 4 },
					{ word: "extraneus", syllables: 4 },
					{ word: "eyecatcher", syllables: 3 },
					{ word: "eyeliner", syllables: 3 },
					{ word: "eyeopener", syllables: 4 },
					{ word: "eyetracker", syllables: 3 },
					{ word: "eyetracking", syllables: 3 },
					{ word: "fairtrade", syllables: 2 },
					{ word: "fauteuil", syllables: 2 },
					{ word: "feature", syllables: 2 },
					{ word: "feuilletee", syllables: 3 },
					{ word: "feuilleton", syllables: 3 },
					{ word: "fisheye", syllables: 2 },
					{ word: "fineliner", syllables: 3 },
					{ word: "finetunen", syllables: 3 },
					{ word: "forehand", syllables: 2 },
					{ word: "freak", syllables: 1 },
					{ word: "fusioneren", syllables: 4 },
					{ word: "gayparade", syllables: 3 },
					{ word: "gaypride", syllables: 2 },
					{ word: "goal", syllables: 1 },
					{ word: "grapefruit", syllables: 2 },
					{ word: "gruyère", syllables: 3 },
					{ word: "guele", syllables: 1 },
					{ word: "guerrilla", syllables: 3 },
					{ word: "guest", syllables: 1 },
					{ word: "hardware", syllables: 2 },
					{ word: "haute", syllables: 1 },
					{ word: "healing", syllables: 2 },
					{ word: "heater", syllables: 2 },
					{ word: "heavy", syllables: 2 },
					{ word: "hoax", syllables: 1 },
					{ word: "hotline", syllables: 2 },
					{ word: "idee-fixe", syllables: 3 },
					{ word: "inclusive", syllables: 3 },
					{ word: "inline", syllables: 2 },
					{ word: "intake", syllables: 2 },
					{ word: "intensive", syllables: 3 },
					{ word: "jeans", syllables: 1 },
					{ word: "Jones", syllables: 1},
					{ word: "jubileum", syllables: 4 },
					{ word: "kalfsribeye", syllables: 3 },
					{ word: "kraaiennest", syllables: 3 },
					{ word: "lastminute", syllables: 3 },
					{ word: "learning", syllables: 2 },
					{ word: "league", syllables: 1 },
					{ word: "line-up", syllables: 2 },
					{ word: "linoleum", syllables: 4 },
					{ word: "load", syllables: 1 },
					{ word: "loafer", syllables: 2 },
					{ word: "longread", syllables: 2 },
					{ word: "lookalike", syllables: 3 },
					{ word: "louis", syllables: 3 },
					{ word: "lyceum", syllables: 3 },
					{ word: "magazine", syllables: 3 },
					{ word: "mainstream", syllables: 2 },
					{ word: "make-over", syllables: 3 },
					{ word: "make-up", syllables: 2 },
					{ word: "malware", syllables: 2 },
					{ word: "marmoleum", syllables: 4 },
					{ word: "mausoleum", syllables: 4 },
					{ word: "medeauteur", syllables: 4 },
					{ word: "midlifecrisis", syllables: 4 },
					{ word: "migraineaura", syllables: 5 },
					{ word: "milkshake", syllables: 2 },
					{ word: "millefeuille", syllables: 4 },
					{ word: "mixed", syllables: 1 },
					{ word: "muesli", syllables: 2 },
					{ word: "museum", syllables: 3 },
					{ word: "must-have", syllables: 2 },
					{ word: "must-read", syllables: 2 },
					{ word: "notebook", syllables: 2 },
					{ word: "nonsense", syllables: 2 },
					{ word: "nowhere", syllables: 2 },
					{ word: "nurture", syllables: 2 },
					{ word: "offline", syllables: 2 },
					{ word: "oneliner", syllables: 3 },
					{ word: "onesie", syllables: 2 },
					{ word: "online", syllables: 2 },
					{ word: "opinion", syllables: 3 },
					{ word: "paella", syllables: 3 },
					{ word: "pacemaker", syllables: 3 },
					{ word: "panache", syllables: 2 },
					{ word: "papegaaienneus", syllables: 5},
					{ word: "passe-partout", syllables: 3 },
					{ word: "peanuts", syllables: 2 },
					{ word: "perigeum", syllables: 4 },
					{ word: "perineum", syllables: 4 },
					{ word: "perpetuum", syllables: 4 },
					{ word: "petroleum", syllables: 4 },
					{ word: "phone", syllables: 3 },
					{ word: "picture", syllables: 2 },
					{ word: "placemat", syllables: 2 },
					{ word: "porte-manteau", syllables: 3 },
					{ word: "portefeuille", syllables: 4 },
					{ word: "presse-papier", syllables: 3 },
					{ word: "primetime", syllables: 2 },
					{ word: "queen", syllables: 1 },
					{ word: "questionnaire", syllables: 3 },
					{ word: "queue", syllables: 1 },
					{ word: "reader", syllables: 2 },
					{ word: "reality", syllables: 3 },
					{ word: "reallife", syllables: 2 },
					{ word: "remake", syllables: 2 },
					{ word: "repeat", syllables: 2 },
					{ word: "repertoire", syllables: 3 },
					{ word: "research", syllables: 2 },
					{ word: "reverence", syllables: 3 },
					{ word: "ribeye", syllables: 2 },
					{ word: "ringtone", syllables: 3 },
					{ word: "road", syllables: 1 },
					{ word: "roaming", syllables: 2 },
					{ word: "sciencefiction", syllables: 4 },
					{ word: "selfmade", syllables: 2 },
					{ word: "sidekick", syllables: 2 },
					{ word: "sightseeing", syllables: 3 },
					{ word: "skyline", syllables: 2 },
					{ word: "smile", syllables: 1 },
					{ word: "sneaky", syllables: 2 },
					{ word: "software", syllables: 2 },
					{ word: "sparerib", syllables: 2 },
					{ word: "speaker", syllables: 2 },
					{ word: "spread", syllables: 1 },
					{ word: "statement", syllables: 2 },
					{ word: "steak", syllables: 1 },
					{ word: "steeplechase", syllables: 3 },
					{ word: "stonewash", syllables: 2 },
					{ word: "store", syllables: 1 },
					{ word: "streaken", syllables: 2 },
					{ word: "stream", syllables: 1 },
					{ word: "streetware", syllables: 1 },
					{ word: "supersoaker", syllables: 4 },
					{ word: "surprise-party", syllables: 4 },
					{ word: "sweater", syllables: 2 },
					{ word: "teaser", syllables: 2 },
					{ word: "tenue", syllables: 2 },
					{ word: "template", syllables: 2 },
					{ word: "timeline", syllables: 2 },
					{ word: "tissue", syllables: 2 },
					{ word: "toast", syllables: 1 },
					{ word: "tête-à-tête", syllables: 3 },
					{ word: "typecast", syllables: 2 },
					{ word: "unique", syllables: 2 },
					{ word: "ureum", syllables: 3 },
					{ word: "vibe", syllables: 1 },
					{ word: "vieux", syllables: 1 },
					{ word: "ville", syllables: 1 },
					{ word: "vintage", syllables: 2 },
					{ word: "wandelyup", syllables: 3 },
					{ word: "wiseguy", syllables: 2 },
					{ word: "wake-up-call", syllables: 3 },
					{ word: "webcare", syllables: 2 },
					{ word: "winegum", syllables: 2 }
				]
			},
			// Word compounds that should only be found at the end.
			compoundEnds: {
				exclusionParts: [
					{ word: "force", syllables: 1 },
					{ word: "tea", syllables: 1 },
					{ word: "time", syllables: 1 }
				],
				matchEnd: true
			},
			// Exclusion words that should be found at the beginning or end of a string.
			exclusionCompounds: {
				exclusionParts: [
					{ word: "byte", syllables: 1 },
					{ word: "cake", syllables: 1 },
					{ word: "care", syllables: 1 },
					{ word: "coach", syllables: 1 },
					{ word: "coat", syllables: 1 },
					{ word: "earl", syllables: 1 },
					{ word: "foam", syllables: 1 },
					{ word: "gate", syllables: 1 },
					{ word: "head", syllables: 1 },
					{ word: "home", syllables: 1 },
					{ word: "live", syllables: 1 },
					{ word: "safe", syllables: 1 },
					{ word: "site", syllables: 1 },
					{ word: "soap", syllables: 1 },
					{ word: "teak", syllables: 1 },
					{ word: "team", syllables: 1 },
					{ word: "wave", syllables: 1 }
				],
				matchBeginning: true,
				matchEnd: true
			},
			// Exclusion words that should be found at the end of the string, including their plurals.
			exclusionsEndPlural: {
				exclusionParts: [
					{ word: "date", syllables: 1 },
					{ word: "hype", syllables: 1 },
					{ word: "quote", syllables: 1 },
					{ word: "tape", syllables: 1 },
					{ word: "upgrade", syllables: 2 }
				],
				matchEnd: true,
				regexEndLetters: [ "", "s" ]
			},
			// Exclusion words that should be found at the begin or end of the string, but not if followed by an 's'.
			exclusionsBeginEndNoS: {
				exclusionParts: [
					{ word: "brace", syllables: 1 },
					{ word: "case", syllables: 1 },
					{ word: "fleece", syllables: 1 },
					{ word: "service", syllables: 2 },
					{ word: "voice", syllables: 1 }

				],
				matchBeginning: true,
				regexBeginLetters: [ "[^s]" ],
				matchEnd: true,
				regexEndLetters: [ "", "[^s]" ]
			},

			// Exclusion words that should be at the beginning of a string, but not if followed by an 's'.
			exclusionsBeginNoS: {
				exclusionParts: [
					{ word: "image", syllables: 2 }
				],
				matchBeginning: true,
				regexBeginLetters: [ "(?![s])" ]
			},

			// Exclusion words that should be found anywhere in a string, but not if followed by an 'n'.
			exclusionsBeginNoN: {
				exclusionParts: [
					{ word: "style", syllables: 1 }
				],
				regexAnywhereLetters: [ "(?![n])" ]
			},
			// Exclusion words that should be found anywhere in a string, but not if followed by an 'n' or 's'.
			exclusionsNoNS: {
				exclusionParts: [
					{ word: "douche", syllables: 1 },
					{ word: "space", syllables: 1 },
					{ word: "striptease", syllables: 2 }
				],
				regexAnywhereLetters: [ "(?![ns])" ]
			},
			// Exclusion words that should be found anywhere in a string, but not if followed by an 'r' or 's'.
			exclusionsNoRS: {
				exclusionParts: [
					{ word: "office", syllables: 2 }
				],
				regexAnywhereLetters: [ "(?![rs])" ]
			},
			// Exclusion words that should be found anywhere in a string, but not if followed by an 'n' or 'r'.
			exclusionsNoNR: {
				exclusionParts: [
					{ word: "jive", syllables: 1 },
					{ word: "keynote", syllables: 2 },
					{ word: "mountainbike", syllables: 3 }
				],
				regexAnywhereLetters: [ "(?![nr])" ]
			},
			// Exclusion words that should be found anywhere in a string, but not if followed by an 'n', 'r' or 's'.
			exclusionsNoNRS: {
				exclusionParts: [
					{ word: "challenge", syllables: 2 },
					{ word: "cruise", syllables: 1 },
					{ word: "house", syllables: 1 },
					{ word: "dance", syllables: 1 },
					{ word: "franchise", syllables: 2 },
					{ word: "freelance", syllables: 2 },
					{ word: "lease", syllables: 1 },
					{ word: "lounge", syllables: 1 },
					{ word: "merchandise", syllables: 3 },
					{ word: "performance", syllables: 3 },
					{ word: "release", syllables: 2 },
					{ word: "resource", syllables: 2 }
				],
				regexAnywhereLetters: [ "(?![nrs])" ]
			},

			// Exclusion words that should be found at the beginning or end of a string, but not if followed by an 'n' or 'r'.
			exclusionsBeginEndNoNR: {
				exclusionParts: [
					{ word: "kite", syllables: 1 },
					{ word: "skate", syllables: 1 }
				],
				matchBeginning: true,
				regexBeginLetters: [ "(?![nr])" ],
				matchEnd: true
			},

			// Exclusion words that should be found at the beginning or end of a string, but not if followed by an 'n', 'r' or 's'.
			exclusionsBeginEndNoNRS: {
				exclusionParts: [
					{ word: "race", syllables: 1 }
				],
				matchBeginning: true,
				regexBeginLetters: [ "(?![nrs])" ]
			}
		},
		vowels: 'aáäâeéëêiíïîoóöôuúüûy'
	}
};

module.exports = function( locale ) {
	if ( isUndefined( locale ) ) {
		locale = "en_US"
	}
	switch( getLanguage( locale ) ) {
		case "nl":
			return syllableLanguageConfig.nl;
		case "en":
		default:
			return syllableLanguageConfig.en;
	}
};
