export const HANDLE_QUERY = "HANDLE_QUERY";
export const HANDLE_QUERY_REQUEST = "HANDLE_QUERY_REQUEST";
export const HANDLE_QUERY_SUCCESS = "HANDLE_QUERY_SUCCESS";
export const HANDLE_QUERY_ERROR = "HANDLE_QUERY_ERROR";

export const HANDLE_MORE_RESULTS_QUERY_REQUEST = "HANDLE_MORE_RESULTS_QUERY_REQUEST";
export const HANDLE_MORE_RESULTS_QUERY_SUCCESS = "HANDLE_MORE_RESULTS_QUERY_SUCCESS";
export const HANDLE_MORE_RESULTS_QUERY_ERROR = "HANDLE_MORE_RESULTS_QUERY_ERROR";

export const GET_DETAIL = "GET_DETAIL";
export const GET_DETAIL_REQUEST = "GET_DETAIL_REQUEST";
export const GET_DETAIL_SUCCESS = "GET_DETAIL_SUCCESS";
export const GET_DETAIL_ERROR = "GET_DETAIL_ERROR";

export const HANDLE_SAVE = "HANDLE_SAVE";
export const HANDLE_SAVE_REQUEST = "HANDLE_SAVE_REQUEST";
export const HANDLE_SAVE_SUCCESS = "HANDLE_SAVE_SUCCESS";
export const HANDLE_SAVE_ERROR = "HANDLE_SAVE_ERROR";

export const SET_QUERY_DATA = "SET_QUERY_DATA";
export const SET_ALL_QUERY_DATA = "SET_ALL_QUERY_DATA";

export const SET_ALL_DATA = "SET_ALL_DATA";
export const SET_DATA = "SET_DATA";
export const REPLACE_ARRAY_DATA = "REPLACE_ARRAY_DATA";
export const TOGGLE_DATA = "TOGGLE_DATA";
export const RESET_DATA = "RESET_DATA";

export const RESET_LIST_DATA = "RESET_LIST_DATA";

export const RUN_ANALYSIS = "RUN_ANALYSIS";
export const RUN_ANALYSIS_REQUEST = "RUN_ANALYSIS_REQUEST";
export const RUN_ANALYSIS_SUCCESS = "RUN_ANALYSIS_SUCCESS";
export const RUN_ANALYSIS_ERROR = "RUN_ANALYSIS_ERROR";

export const SET_MARKER = "SET_MARKER";
export const RESET_MARKER = "RESET_MARKER";

export const RUN_RELATED_KEYPHRASE_ANALYSIS = "RUN_RELATED_KEYPHRASE_ANALYSIS";
export const RUN_RELATED_KEYPHRASE_ANALYSIS_REQUEST = "RUN_RELATED_KEYPHRASE_ANALYSIS_REQUEST";
export const RUN_RELATED_KEYPHRASE_ANALYSIS_SUCCESS = "RUN_RELATED_KEYPHRASE_ANALYSIS_SUCCESS";
export const RUN_RELATED_KEYPHRASE_ANALYSIS_ERROR = "RUN_RELATED_KEYPHRASE_ANALYSIS_ERROR";

export const ADD_RELATED_KEYPHRASE = "ADD_RELATED_KEYPHRASE";
export const REMOVE_RELATED_KEYPHRASE = "REMOVE_RELATED_KEYPHRASE";

export const RUN_RESEARCH = "RUN_RESEARCH";
export const RUN_RESEARCH_REQUEST = "RUN_RESEARCH_REQUEST";
export const RUN_RESEARCH_SUCCESS = "RUN_RESEARCH_SUCCESS";
export const RUN_RESEARCH_ERROR = "RUN_RESEARCH_ERROR";

export const HANDLE_ROUTE_CHANGED = "HANDLE_ROUTE_CHANGED";
export const HANDLE_ROUTE_CHANGED_REQUEST = "HANDLE_ROUTE_CHANGED_REQUEST";
export const HANDLE_ROUTE_CHANGED_SUCCESS = "HANDLE_ROUTE_CHANGED_SUCCESS";
export const HANDLE_ROUTE_CHANGED_ERROR = "HANDLE_ROUTE_CHANGED_ERROR";

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";
