<?php
// phpcs:disable Yoast.NamingConventions.NamespaceName.TooLong
namespace Yoast\WP\SEO\Llms_Txt\Infrastructure\File;

use Yoast\WP\SEO\Helpers\Options_Helper;
use Yoast\WP\SEO\Llms_Txt\Domain\File\Llms_Txt_Permission_Gate_Interface;

/**
 * Handles checks to see if we manage the llms.txt file.
 */
class WordPress_Llms_Txt_Permission_Gate implements Llms_Txt_Permission_Gate_Interface {

	/**
	 * The file system adapter.
	 *
	 * @var WordPress_File_System_Adapter
	 */
	private $file_system_adapter;

	/**
	 * The options helper.
	 *
	 * @var Options_Helper
	 */
	private $options_helper;

	/**
	 * Constructor.
	 *
	 * @param WordPress_File_System_Adapter $file_system_adapter The file system adapter.
	 * @param Options_Helper                $options_helper      The options helper.
	 */
	public function __construct(
		WordPress_File_System_Adapter $file_system_adapter,
		Options_Helper $options_helper
	) {
		$this->file_system_adapter = $file_system_adapter;
		$this->options_helper      = $options_helper;
	}

	/**
	 * Checks if the llms.txt can be regenerated.
	 *
	 * @return bool If the llms.txt can be regenerated.
	 */
	public function can_regenerate(): bool {
		$stored_hash = $this->options_helper->get( 'llms_txt_content_hash', '' );

		// Check file editing permissions.
		if ( !$this->file_system_adapter->is_file_system_available() ) {
			return false;
		}

		// If the file does not exist yet, we always regenerate/create it.
		if ( ! $this->file_system_adapter->file_exists() ) {
			return true;
		}

		$current_content = $this->file_system_adapter->get_file_contents();

		// If you have a hash, we want to make sure it's the same. This check makes sure the file is not edited by the user.
		if ( $stored_hash !== '' ) {
			return \md5( $current_content ) === $stored_hash;
		}

		// If there is no hash for some reason, we want to double-check if it might be our file.
		return \strpos( $current_content, 'Generated by Yoast SEO' ) !== false;
	}
}
