name: Build Plugin Zip

on:
  workflow_dispatch:

jobs:
  build:
    name: "Build plugin zip"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: './.nvmrc'

      - name: Yarn install
        run: yarn install

      - name: "Grunt: create artifact"
        run: grunt artifact

      - name: Create zip
        run: |
          cd artifact
          zip -r ../wordpress-seo.zip .

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: wordpress-seo
          path: wordpress-seo.zip
          retention-days: 1
          overwrite: true
