name: LintJS

on:
  # Run on relevant pushes to select branches and on all relevant pull requests.
  push:
    branches:
      - main
      - trunk
      - 'release/**'
      - 'hotfix/[0-9]+.[0-9]+*'
      - 'feature/**'
    paths:
      - '**.js' # Includes Gruntfile.js.
      - '.browserslistrc'
      - '.eslintignore'
      - '.eslintrc'
      - '.nvmrc'
      - '.yarnrc'
      - 'lerna.json'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/jslint.yml'
      - '.yarn/**'
      - 'apps/**'
      - 'config/grunt/**'
      - 'packages/**'
  pull_request:
    paths:
      - '**.js' # Includes Gruntfile.js.
      - '.browserslistrc'
      - '.eslintignore'
      - '.eslintrc'
      - '.nvmrc'
      - '.yarnrc'
      - 'lerna.json'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/jslint.yml'
      - '.yarn/**'
      - 'apps/**'
      - 'config/grunt/**'
      - 'packages/**'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  yarn-lint:
    runs-on: ubuntu-latest

    name: "LintJS"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # The ubuntu images come with Node, npm and yarn pre-installed.
      # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md

      # This action also handles the caching of the Yarn dependencies.
      # https://github.com/actions/setup-node
      - name: Set up node and enable caching of dependencies
        uses: actions/setup-node@v4
        with:
          node-version-file: './.nvmrc'
          cache: 'yarn'

      - name: Yarn install
        run: yarn install

      - name: Show debug info
        run: |
          npm --version
          node --version
          yarn --version
          grunt --version

      - name: Run Javascript lint
        run: yarn lint
