name: "Close stale issues"
on:
  schedule:
  - cron: "00 9 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days'
        days-before-stale: 30
        days-before-close: 5
        exempt-issue-labels: 'awaiting-approval,work-in-progress,help-wanted,good-first-issue,help wanted,good first issue'
        exempt-pr-labels: 'awaiting-approval,work-in-progress'
